import itertools

from beartype import beartype
from beartype.typing import (
    Any,
    Dict,
    Generator,
    Iterable,
    List,
    Optional,
    Sequence,
    Tuple,
)
from py_codegen import codegen_ir
import py_codegen.astbuilder_cpp as cpp
from py_codegen.codegen_ir import QualType
from py_haxorg.layout.wrap import BlockId, TextLayout, TextOptions
from py_scriptutils.algorithm import drop_none, iterate_object_tree

PROTO_VALUE_NAME = "out"
ORG_VALUE_NAME = "in"


@beartype
class ProtoBuilder():

    def __init__(
        self,
        wrapped: Sequence[codegen_ir.GenTuUnion],
        ast: cpp.ASTBuilder,
        type_map: codegen_ir.GenTypeMap,
    ):
        self.type_map = type_map
        self.ast = ast
        self.t = ast.b

        self.enum_type_list: List[QualType] = []
        self.variant_type_list: Dict[Tuple[str, ...], codegen_ir.GenTuTypedef] = {}
        self.types_list = wrapped

        context: List[QualType] = []

        def find_enums(obj: Any) -> None:
            if isinstance(obj, codegen_ir.GenTuEnum):
                filter = codegen_ir.filter_walk_scope(context)
                self.enum_type_list.append(obj.name)

            elif isinstance(obj, codegen_ir.GenTuTypedef):
                if obj.base.Name == "variant":
                    self.variant_type_list[tuple(obj.name.flatQualName())] = obj

        iterate_object_tree(self.types_list, context, pre_visit=find_enums)

    def oneof_field_name(self, it: codegen_ir.GenTuField) -> str:
        if it.Type and it.Type.Name == "Variant":
            return it.Name + "_kind"

        else:
            return "kind"

    def build_protobuf(self) -> BlockId:

        def braced(name: str, content: Iterable[BlockId]) -> BlockId:
            return self.t.stack([
                self.t.text(f"{name} {{"),
                self.t.indent(2, self.t.stack(list(content))),
                self.t.text("}"),
            ])

        field_name_width = 32
        field_type_width = 48
        enum_field_width = field_name_width + field_type_width

        def aux_field(it: codegen_ir.GenTuField, indexer: Generator[int],
                      indent: int) -> BlockId:
            assert it.Type, "Missing type for the field"
            if it.Type.Name == "Variant":
                return self.t.stack([
                    braced(
                        f"oneof {self.oneof_field_name(it)}",
                        aux_field_list(
                            self.build_protobuf_fields_for_variant(it.Type),
                            indexer=indexer,
                            indent=indent + 1,
                        ))
                ])

            else:
                type_width = field_type_width - (2 * indent)
                idx = next(indexer)
                return self.t.text(
                    f"{self.rewrite_for_proto_grammar(it.Type):<{type_width}} {it.Name:<{field_name_width}} = {idx + 1};"
                )

        def aux_enum(parent: codegen_ir.GenTuEnum, it: codegen_ir.GenTuEnumField,
                     idx: int, indent: int) -> BlockId:
            # _f suffix to avoid clashes with OrgSpecName_Name method generated by protoc
            name = f"{parent.Name.Name}_{it.Name}_f"
            enum_width = enum_field_width - 2 * indent
            return self.t.text(f"{name:<{enum_width}}  = {idx};")

        def aux_field_list(fields: Iterable[codegen_ir.GenTuField],
                           indexer: Generator[int], indent: int) -> Iterable[BlockId]:
            return (aux_field(field, indexer, indent=indent) for field in fields)

        def make_full_enumerator() -> Generator[int]:

            def full_enumerator() -> Generator[int]:
                value = 0
                while True:
                    yield value
                    value += 1

            return full_enumerator()

        def aux_item(it: codegen_ir.GenTuEntry | codegen_ir.GenTuField,
                     indent: int) -> Optional[BlockId]:
            match it:
                case codegen_ir.GenTuStruct():
                    return braced(
                        "message " + it.Name.name,
                        itertools.chain(
                            drop_none(
                                aux_item(sub, indent=indent + 1) for sub in it.Nested),
                            aux_field_list(
                                (codegen_ir.get_type_base_fields(it, self.type_map) +
                                 it.Fields),
                                indexer=make_full_enumerator(),
                                indent=indent), [
                                    aux_field(
                                        it=codegen_ir.GenTuField(
                                            QualType.ForName("Str"), "debug"),
                                        indexer=(it for it in [999]),
                                        indent=indent,
                                    )
                                ]))

                case codegen_ir.GenTuEnum():
                    return braced("enum " + it.Name.name, [
                        aux_enum(it, sub, idx, indent)
                        for idx, sub in enumerate(it.Fields)
                    ])

                case codegen_ir.GenTuPass():
                    return None

                case codegen_ir.GenTuTypedef():
                    match it.Base:
                        case QualType(Name="variant"):
                            return braced("message " + it.Name.name, [
                                braced(
                                    "oneof kind",
                                    aux_field_list(
                                        (codegen_ir.GenTuField(Name=par.Name.lower(),
                                                               Type=par)
                                         for par in it.Base.Params),
                                        indexer=make_full_enumerator(),
                                        indent=indent + 1))
                            ])

                        case _:
                            return None

                case _:
                    assert False, type(it)

        any_node = braced("message AnyNode", [
            braced(
                "oneof kind",
                aux_field_list(
                    (codegen_ir.GenTuField(Name=rec.Name.Name.lower(), Type=rec.Name)
                     for rec in self.get_all_concrete_types()),
                    indent=0,
                    indexer=make_full_enumerator()),
            )
        ])

        return self.t.stack(
            list(
                itertools.chain(*([it, self.t.text("")] for it in drop_none(
                    aux_item(it, indent=0) for it in self.types_list)))) + [any_node])

    @beartype
    def get_all_concrete_types(self) -> Iterable[codegen_ir.GenTuStruct]:
        return (rec for rec in self.types_list
                if isinstance(rec, codegen_ir.GenTuStruct) and not rec.IsAbstract and
                rec.Name.isOrgType())

    @beartype
    def get_any_node_field_mapping(self) -> cpp.MacroParams:
        return cpp.MacroParams(
            name="EACH_ANY_NODE_PROTO_FIELD",
            params=[cpp.MacroParams.Param("__MAP")],
            definition=[
                "__MAP(k{}, {}, {})".format(
                    rec.Name.Name.capitalize(),
                    self.sanitize_ident_for_protobuf(rec.Name.Name),
                    rec.Name.Name,
                ) for rec in self.get_all_concrete_types()
            ],
        )

    @beartype
    def rewrite_for_proto_grammar(self, it: QualType) -> str:
        match it.Name:
            case "Vec":
                return "repeated " + self.rewrite_for_proto_grammar(it.Params[0])

            case "Str" | "string":
                return "string"

            case "int":
                return "int32"

            case "Opt" | "optional":
                if it.Params[0].Name == "Vec":
                    return self.rewrite_for_proto_grammar(it.Params[0])

                else:
                    return "optional " + self.rewrite_for_proto_grammar(it.Params[0])

            case "UnorderedMap":
                return "map<{}, {}>".format(
                    self.rewrite_for_proto_grammar(it.Params[0]),
                    self.rewrite_for_proto_grammar(it.Params[1]),
                )

            case "SemId":
                par0 = it.par0()
                assert par0, "SemId template type must have a template parameter"
                if par0.Name == "Org":
                    return "AnyNode"

                else:
                    return self.rewrite_for_proto_grammar(it.Params[0])

            case _:
                spaces = [s.Name for s in it.Spaces if s.Name != "sem"]
                return ".".join(spaces + [it.Name])

    @beartype
    def rewrite_for_proto_serde(
        self,
        typ: QualType,
    ) -> QualType:

        def aux_parameters(typ: QualType) -> List[QualType]:
            return [self.rewrite_for_proto_serde(p) for p in typ.Params]

        match typ:
            case QualType(Name="SemId", Params=[nodeType]):
                if nodeType.Name == "Org":
                    return QualType.ForName("AnyNode").withExtraSpace("orgproto")

                else:
                    return nodeType.withoutSpace("sem").withoutSpace(
                        "org").withExtraSpace("orgproto")

            case QualType(Name="bool"):
                return typ

            case QualType(Name="Str"):
                return QualType.ForName("string").withExtraSpace("std")

            case QualType(Name="int"):
                return QualType.ForName("int32_t").withGlobalSpace()

            case QualType(Name="Vec"):
                if typ.Params[0].Name in ["int", "bool"]:
                    wrap_type = "RepeatedField"

                else:
                    wrap_type = "RepeatedPtrField"

                return typ.model_copy(update=dict(
                    Parameters=aux_parameters(typ),
                    name=wrap_type,
                    Spaces=[QualType.ForName("google"),
                            QualType.ForName("protobuf")],
                    isGlobalNamespace=True,
                ))

            case QualType(Name="UnorderedMap"):
                return typ.model_copy(update=dict(
                    Parameters=aux_parameters(typ),
                    name="Map",
                    Spaces=[QualType.ForName("google"),
                            QualType.ForName("protobuf")],
                    isGlobalNamespace=True,
                ))

            case _:
                if codegen_ir.in_type_list(typ, self.enum_type_list):
                    return QualType.ForName("_".join(
                        typ.withoutSpace("sem").withoutSpace(
                            "org").flatQualName())).withExtraSpace("orgproto")

                # FIXME Undocumented hardcoded list of types, easily breaking
                # when adding new data shared between cxx and protobuf type
                # definitions.
                elif typ.Name == "SourceLoc":
                    result = typ.model_copy(update=dict(Parameters=aux_parameters(typ),
                                                        Spaces=[
                                                            QualType.ForName("orgproto"),
                                                            QualType.ForName("org_parse"),
                                                        ]))

                    return result

                else:
                    result = typ.model_copy(update=dict(Parameters=aux_parameters(typ)))
                    if "sem" in result.flatSpaceNames() or typ.Name in ["UserTime"]:
                        result = result.withoutSpace("sem").withoutSpace(
                            "org").withExtraSpace("orgproto")

                    return result

    @beartype
    def build_protobuf_cxx_field_read(
        self,
        field: codegen_ir.GenTuField,
        dot_field: BlockId,
        is_read_getter: bool,
    ) -> Tuple[BlockId, QualType, QualType]:
        assert field.Type
        if not is_read_getter and field.Type.Name in ["Opt"]:
            field_read = self.t.line([self.t.text("*"), dot_field])
            field_type = field.Type.Params[0]

        else:
            field_read = dot_field
            field_type = field.Type

        # if not is_read_getter and field_type.name == "SemId":
        #     field_read = self.t.line(
        #         [self.t.text("*(("), field_read,
        #          self.t.text(").get())")])
        #     field_type = field_type.Parameters[0]

        field_proto_type = self.rewrite_for_proto_serde(field_type)
        is_enum_field = codegen_ir.in_type_list(field_type, self.enum_type_list)

        if not is_read_getter and is_enum_field:
            field_read = self.ast.XCall(
                "static_cast",
                args=[field_read],
                Params=[field_proto_type],
            )

        return (field_read, field_type, field_proto_type)

    def is_enum_type(self, typ: QualType) -> bool:
        return codegen_ir.in_type_list(typ, self.enum_type_list)

    def is_direct_set_type(self, typ: QualType) -> bool:
        return typ.Name in ["int", "string", "bool", "float"] or self.is_enum_type(typ)

    def get_field_read_op(
        self,
        field: codegen_ir.GenTuField,
        dot_field: BlockId,
        parent_field: Optional[codegen_ir.GenTuField] = None,
    ) -> BlockId:
        field_read, field_type, field_proto_type = self.build_protobuf_cxx_field_read(
            field,
            dot_field,
            is_read_getter=True,
        )

        proto_ptr = self.ast.b.text(PROTO_VALUE_NAME)

        if self.is_direct_set_type(field_type):
            read_expr = self.ast.XCallRef(proto_ptr,
                                          self.sanitize_ident_for_protobuf(field.Name))
            if self.is_enum_type(field_type):
                read_expr = self.ast.XCall(
                    "static_cast",
                    args=[read_expr],
                    Params=[field_type],
                )

            read_op = self.t.line([
                self.ast.XCallRef(field_read, "get"),
                self.t.text(" = "),
                read_expr,
                self.t.text(";"),
            ])

        else:
            opc = self.sanitize_ident_for_protobuf(field.Name)

            if parent_field:
                opc = self.sanitize_ident_for_protobuf(parent_field.Name) + "()." + opc

            read_op = self.ast.CallStatic(
                QualType(
                    Name="proto_serde",
                    Params=[field_proto_type, field_type],
                ),
                "read",
                [
                    self.ast.XCallRef(proto_ptr, opc),
                    field_read,
                ],
                Stmt=True,
            )

        assert field.Type
        if field.Type.Name in ["Opt"]:
            par0 = field.Type.par0()
            assert par0
            if par0.Name not in ["Vec"]:
                read_op = self.ast.IfStmt(
                    cpp.IfStmtParams([
                        cpp.IfStmtParams.Branch(
                            Cond=self.ast.XCallRef(
                                proto_ptr,
                                "has_" + self.sanitize_ident_for_protobuf(field.Name),
                            ),
                            Then=read_op,
                        )
                    ]))

        return read_op

    def get_field_write_op(
        self,
        field: codegen_ir.GenTuField,
        dot_field: BlockId,
        parent_field: Optional[codegen_ir.GenTuField] = None,
    ) -> BlockId:
        field_read, field_type, field_proto_type = self.build_protobuf_cxx_field_read(
            field,
            dot_field,
            is_read_getter=False,
        )

        if self.is_direct_set_type(field_type):
            write_op = self.ast.XCallPtr(
                self.ast.b.text(PROTO_VALUE_NAME),
                "set_" + self.sanitize_ident_for_protobuf(field.Name),
                [field_read],
                Stmt=True,
            )

        else:
            if parent_field:
                opc = f"mutable_{self.sanitize_ident_for_protobuf(parent_field.Name)}()->mutable_{self.sanitize_ident_for_protobuf(field.Name)}"

            else:
                opc = "mutable_" + self.sanitize_ident_for_protobuf(field.Name)

            if self.sanitize_ident_for_protobuf(field.Name) in ["static", "export"]:
                opc += "_"

            write_op = self.ast.CallStatic(
                QualType(
                    Name="proto_serde",
                    Params=[field_proto_type, field_type],
                ),
                "write",
                [self.ast.XCallPtr(self.ast.b.text(PROTO_VALUE_NAME), opc), field_read],
                Stmt=True,
            )

        assert field.Type
        if field.Type.Name in ["Opt"]:
            write_op = self.ast.IfStmt(
                cpp.IfStmtParams(
                    [cpp.IfStmtParams.Branch(
                        Cond=dot_field,
                        Then=write_op,
                    )]))

        elif field.Type.Name.startswith("SemId"):
            write_op = self.ast.IfStmt(
                cpp.IfStmtParams([
                    cpp.IfStmtParams.Branch(
                        Cond=self.t.line([
                            self.t.text("!"),
                            self.ast.XCallRef(dot_field, "isNil"),
                        ]),
                        Then=write_op,
                    )
                ]))

        return write_op

    @beartype
    def build_protobuf_writer_for_field(
        self,
        field: codegen_ir.GenTuField,
        proto_type: QualType,
        org_type: QualType,
    ) -> Tuple[BlockId, BlockId]:
        t = self.ast.b
        field_ptr = self.t.line([
            self.t.text("&"),
            self.ast.Type(org_type),
            self.t.text("::"),
            t.text(field.Name),
        ])

        dot_write = self.ast.Dot(t.text(ORG_VALUE_NAME), t.text(field.Name))
        dot_read = self.ast.XCallRef(
            t.text(ORG_VALUE_NAME),
            "for_field",
            [field_ptr],
        )

        assert field.Type is not None, "Field type must not be None"
        flat = tuple(field.Type.flatQualName())
        if flat in self.variant_type_list or field.Type.Name in [
                "variant", "Variant", "Var"
        ]:
            is_typedef = flat in self.variant_type_list
            variant = self.variant_type_list[flat].base if is_typedef else field.Type
            assert variant is not None, "Variant type must not be None"
            if is_typedef:
                reader_switch = cpp.SwitchStmtParams(Expr=self.ast.XCallRef(
                    t.text(PROTO_VALUE_NAME),
                    self.sanitize_ident_for_protobuf(field.Name) + "()." +
                    self.oneof_field_name(field) + "_case"))

            else:
                reader_switch = cpp.SwitchStmtParams(
                    Expr=self.ast.XCallRef(t.text(PROTO_VALUE_NAME),
                                           self.oneof_field_name(field) + "_case"))

            writer_switch = cpp.SwitchStmtParams(
                Expr=t.line([dot_write, t.text(".index()")]))

            if is_typedef:
                assert field.Type is not None, "Field type must not be None"
                kind_type = proto_type.asSpaceFor(
                    field.Type.withoutAllScopeQualifiers())  # type: ignore

            else:
                kind_type = proto_type

            for idx, var_field in enumerate(
                    self.build_protobuf_fields_for_variant(variant)):

                var_dot_write = t.line(
                    [t.text(f"std::get<{idx}>("), dot_write,
                     t.text(")")])
                var_dot_read = t.line([
                    self.ast.XCallRef(
                        t.text(ORG_VALUE_NAME),
                        "for_field_variant",
                        [field_ptr],
                        Params=[QualType.ForExpr(str(idx))],
                    )
                ])

                writer_switch.Cases.append(
                    cpp.CaseStmtParams(
                        Expr=t.text(str(idx)),
                        Body=[
                            self.get_field_write_op(
                                var_field,
                                var_dot_write,
                                parent_field=field if is_typedef else None,
                            )
                        ],
                        OneLine=False,
                        Compound=False,
                        Autobreak=True,
                    ))

                field_enum_value = kind_type.asSpaceFor(
                    cpp.QualType.ForName(f"k{var_field.Name.capitalize()}"))

                reader_switch.Cases.append(
                    cpp.CaseStmtParams(
                        Expr=self.ast.Type(field_enum_value),
                        Body=[
                            self.ast.Call(
                                self.ast.Dot(var_dot_read, self.ast.string("get")),
                                Stmt=True,
                            ),
                            self.get_field_read_op(
                                var_field,
                                var_dot_read,
                                parent_field=field if is_typedef else None,
                            ),
                        ],
                        OneLine=False,
                        Compound=False,
                        Autobreak=True,
                    ))

            reader_switch.Cases.append(
                cpp.CaseStmtParams(
                    Expr=self.ast.Type(
                        kind_type.asSpaceFor(cpp.QualType.ForName("KIND_NOT_SET"))),
                    Body=[
                        self.ast.Throw(
                            self.ast.CallStatic(
                                typ=cpp.QualType(Name="::hstd::logic_assertion_error"),
                                opc="init",
                                Args=[
                                    self.ast.StringLiteral(
                                        "Invalid incoming data -- KIND_NOT_SET for parsing variant field"
                                    ),
                                ],
                            ))
                    ]))

            return (
                self.ast.SwitchStmt(writer_switch),
                self.ast.SwitchStmt(reader_switch),
            )

        else:
            return (
                self.get_field_write_op(
                    field,
                    dot_write,
                ),
                self.get_field_read_op(
                    field,
                    dot_read,
                ),
            )

    @beartype
    def sanitize_ident_for_protobuf(self, ident: str) -> str:
        result = ident.lower().replace(" ", "_")
        if result in ["export", "static"]:
            result += "_"

        return result

    @beartype
    def build_protobuf_fields_for_variant(
        self,
        typ: QualType,
    ) -> Iterable[codegen_ir.GenTuField]:
        return (codegen_ir.GenTuField(
            Name=self.rewrite_for_proto_grammar(
                sub.withoutAllScopeQualifiers()).lower().replace(" ", "_"),
            Type=sub,
        ) for sub in typ.Params)

    @beartype
    def build_protobuf_serde_object(
        self, it: codegen_ir.GenTuUnion | codegen_ir.GenTuPass
    ) -> List[Tuple[cpp.RecordParams, QualType]]:
        result: List[Tuple[cpp.RecordParams, QualType]] = []
        match it:
            case codegen_ir.GenTuStruct():
                if it.IsAbstract:
                    return []

                out = self.t.text(PROTO_VALUE_NAME)
                _in = self.t.text(ORG_VALUE_NAME)
                org_cleaned = it.Name.withoutSpace("sem").withoutSpace(
                    "org").withExtraSpace("orgproto")
                proto_param_type = org_cleaned.withGlobalSpace()
                org_param_type = it.Name

                writer_body: List[BlockId] = []
                reader_body: List[BlockId] = []
                for base in codegen_ir.get_base_list(it, self.type_map):
                    base_type = self.type_map.get_one_type_for_name(base.Name)
                    assert base_type is None or isinstance(
                        base_type,
                        codegen_ir.GenTuStruct), "Base type must be GenTuStruct or None"
                    if base_type and len(base_type.Fields) == 0:
                        continue

                    writer_body.append(
                        self.ast.CallStatic(
                            QualType(
                                Name="proto_serde",
                                Params=[proto_param_type, base],
                                Spaces=[codegen_ir.n_org_algo()],
                            ),
                            "write",
                            [out, _in],
                            Stmt=True,
                        ))

                    reader_body.append(
                        self.ast.CallStatic(
                            QualType(
                                Name="proto_serde",
                                Params=[proto_param_type, base],
                                Spaces=[codegen_ir.n_org_algo()],
                            ),
                            "read",
                            [
                                out,
                                self.ast.XCallRef(_in, "as", Params=[base]),
                            ],
                            Stmt=True,
                        ))

                for field in it.Fields:
                    if field.Name == "staticKind":
                        continue

                    write_op, read_op = self.build_protobuf_writer_for_field(
                        field,
                        proto_type=proto_param_type,
                        org_type=org_param_type,
                    )

                    writer_body.append(write_op)
                    reader_body.append(read_op)

                reader = cpp.MethodDeclParams(
                    Params=cpp.FunctionParams(
                        Name="read",
                        Args=[
                            cpp.ParmVarParams(
                                name=PROTO_VALUE_NAME,
                                type=proto_param_type.asConstRef(),
                            ),
                            cpp.ParmVarParams(
                                name=ORG_VALUE_NAME,
                                type=QualType(
                                    Name="proto_write_accessor",
                                    Params=[org_param_type],
                                ),
                            ),
                        ],
                        doc=cpp.DocParams(""),
                        Body=reader_body,
                        AllowOneLine=False,
                    ),
                    IsStatic=True,
                )

                writer = cpp.MethodDeclParams(
                    Params=cpp.FunctionParams(
                        Name="write",
                        Args=[
                            cpp.ParmVarParams(
                                name=PROTO_VALUE_NAME,
                                type=proto_param_type.asPtr(),
                            ),
                            cpp.ParmVarParams(
                                name=ORG_VALUE_NAME,
                                type=org_param_type.asConstRef(),
                            ),
                        ],
                        doc=cpp.DocParams(""),
                        Body=writer_body,
                        AllowOneLine=False,
                    ),
                    IsStatic=True,
                )

                for sub in it.Nested:
                    assert isinstance(
                        sub,
                        (codegen_ir.GenTuStruct, codegen_ir.GenTuEnum,
                         codegen_ir.GenTuTypedef, codegen_ir.GenTuFunction,
                         codegen_ir.GenTuPass
                        )), "Sub must be a valid type for build_protobuf_serde_object"
                    result += self.build_protobuf_serde_object(sub)

                writer_specialization = QualType(
                    Name="proto_serde",
                    Params=[proto_param_type, org_param_type],
                    Spaces=[codegen_ir.n_org_algo()],
                )

                result.append((
                    cpp.RecordParams(
                        name=cpp.QualType(
                            Name="proto_serde",
                            Spaces=[codegen_ir.n_org_algo()],
                        ),
                        doc=cpp.DocParams(""),
                        NameParams=[proto_param_type, org_param_type],
                        members=[
                            writer,
                            reader,
                        ],
                        Template=codegen_ir.GenTuTemplateParams(
                            Stacks=[codegen_ir.GenTuTemplateGroup(Params=[])]),
                        IsTemplateSpecialization=True,
                    ),
                    writer_specialization,
                ))

        return result

    @beartype
    def build_protobuf_writer(
            self) -> Tuple[Iterable[cpp.RecordParams], Iterable[cpp.MethodDefParams]]:

        item: cpp.RecordParams
        name: QualType
        writer_types: List[cpp.RecordParams] = []
        writer_methods: List[cpp.MethodDefParams] = []
        for item, name in itertools.chain(
                *(self.build_protobuf_serde_object(it) for it in self.types_list)):
            writer_types.append(item)

            for meth in item.methods():
                writer_methods.append(meth.asMethodDef(name))  # type: ignore
                meth.Params.Body = None

        return (writer_types, writer_methods)
