"""
Reading protobuf files generated by the reflection tool.
"""

from copy import copy
from dataclasses import dataclass, field, fields
import enum
import json
from pathlib import Path
import re

from beartype import beartype
from beartype.typing import Any, List, Optional
import betterproto
from betterproto.lib.google import protobuf as pb_google
from py_codegen import codegen_ir
from py_codegen.codegen_ir import QualType
import py_codegen.proto_lib as pb
from py_scriptutils.script_logging import ExceptionContextNote, log

CAT = __name__


@beartype
def conv_proto_default(value: pb.Expr) -> Optional[str]:
    if value.kind == pb.ExprKind.Lit and 0 < len(value.value):
        return value.value

    else:
        return None


@beartype
def strip_comment_prefixes(comment: str) -> List[str]:

    def drop_leading(prefix: re.Pattern, text: str) -> List[str]:
        result: List[str] = []
        for line in text.strip().splitlines():
            result.append(re.sub(prefix, "", line))

        return result

    # Identify and strip comment markers, then delegate to process_content
    if comment.startswith("///") or comment.startswith("//!"):
        return drop_leading(re.compile("///?<?!?\\s*"), comment)
    elif comment.startswith("/**") or comment.startswith("/*!"):
        # Removing the leading /** or /*! and trailing */
        content = comment[3:-2].strip()
        # Remove any '*' prefixes that might exist on each line
        content = "\n".join(line.strip().lstrip("* ") for line in content.splitlines())
        return content.splitlines()
    elif comment.startswith("//"):
        return comment[2:].splitlines()
    elif comment.startswith("/*"):
        # Removing the leading /* and potential trailing */
        content = comment[2:]
        if content.endswith("*/"):
            content = content[:-2]
        content = "\n".join(line.strip().lstrip("* ") for line in content.splitlines())
        return content.splitlines()
    else:
        raise ValueError(f"Unrecognized comment style: {comment}")


@beartype
def conv_doc_comment(comment: str) -> codegen_ir.GenTuDoc:
    if not comment:
        return codegen_ir.GenTuDoc("")

    # Helper function to process content after stripping comment markers
    def process_content(content: List[str]) -> codegen_ir.GenTuDoc:
        brief, full = [], []
        is_brief = True

        for line in content:
            line = line.strip()
            if not line:
                is_brief = False
                continue

            if is_brief:
                brief.append(line)
            else:
                full.append(line)

        return codegen_ir.GenTuDoc("\n".join(brief), "\n".join(full))

    return process_content(strip_comment_prefixes(comment))


@beartype
def conv_proto_type(typ: pb.QualType, is_anon_name: bool = False) -> QualType:
    res: QualType = QualType(Name=typ.name)
    res.DbgOrigin = typ.dbg_origin

    for space in typ.spaces:
        res.Spaces.append(conv_proto_type(space))

    match typ.kind:
        case pb.TypeKind.RegularType:
            res.IsBuiltin = typ.is_builtin
            for param in typ.parameters:
                res.Params.append(conv_proto_type(param))

            # if not is_anon_name:
            #     assert res.name != "", typ

        case pb.TypeKind.FunctionPtr:
            res.Kind = codegen_ir.QualTypeKind.FunctionPtr
            res.Func = QualType.Function(
                ReturnType=conv_proto_type(typ.parameters[0]),
                Args=[conv_proto_type(Arg) for Arg in typ.parameters[1:]]
                if 1 < len(typ.parameters) else [])

        case pb.TypeKind.Array:
            res.Kind = codegen_ir.QualTypeKind.Array
            res.Params = [conv_proto_type(t) for t in typ.parameters]

        case pb.TypeKind.TypeExpr:
            res.Kind = codegen_ir.QualTypeKind.TypeExpr
            res.Expr = typ.type_value.value

    res.IsConst = any([it.is_const for it in typ.qualifiers])
    res.IsNamespace = typ.is_namespace
    res.IsGlobalNamespace = typ.is_global_namespace
    res.RefKind = {
        pb.ReferenceKind.NotRef: codegen_ir.ReferenceKind.NotRef,
        pb.ReferenceKind.LValue: codegen_ir.ReferenceKind.LValue,
        pb.ReferenceKind.RValue: codegen_ir.ReferenceKind.RValue,
    }[typ.ref_kind]

    res.IsTemplateTypeParam = typ.is_template_type_param
    res.IsTemplateInjectedType = typ.is_template_injected_type

    res.PtrCount = len([it for it in typ.qualifiers if it.is_pointer])

    return res


def unwrap_struct_value(val: Any) -> Any:
    if isinstance(val, dict):
        if "structValue" in val:
            return unwrap_struct_value(val["structValue"])
        if "listValue" in val:
            return [unwrap_struct_value(v) for v in val["listValue"].get("values", [])]
        if "stringValue" in val:
            return val["stringValue"]
        if "numberValue" in val:
            return val["numberValue"]
        if "boolValue" in val:
            return val["boolValue"]
        if "nullValue" in val:
            return None
        return {k: unwrap_struct_value(v) for k, v in val.items()}
    return val


@beartype
def conv_proto_reflection_params(
        reflection_params: Optional[pb_google.Struct]) -> codegen_ir.GenTuReflParams:
    if reflection_params:
        refl_dict = unwrap_struct_value(reflection_params.to_dict())
        with ExceptionContextNote(f"Original text is '{refl_dict}'"):
            return codegen_ir.GenTuReflParams.model_validate(refl_dict)

    else:
        return codegen_ir.GenTuReflParams()


@beartype
def conv_proto_templates(
        templates: list[pb.TemplateParams]) -> codegen_ir.GenTuTemplateParams:
    TemplateParams = codegen_ir.GenTuTemplateParams(Stacks=[])
    for proto_template_params in templates:
        for proto_group in proto_template_params.stacks:
            group = codegen_ir.GenTuTemplateGroup()
            for proto_param in proto_group.params:
                kind = codegen_ir.TemplateParamKind(
                    proto_param.kind.name.removeprefix("TEMPLATE_PARAM_KIND_").title())

                type_expr = conv_proto_type(proto_param.type_expr)

                default_value = None
                if proto_param.default:
                    default_value = conv_proto_type(proto_param.default[0])

                nested_template_params = None
                if proto_param.template_params:
                    nested_template_params = codegen_ir.GenTuTemplateParams(Stacks=[])
                    for nested_proto_template_params in proto_param.template_params:
                        for nested_proto_group in nested_proto_template_params.stacks:
                            nested_group = codegen_ir.GenTuTemplateGroup()
                            for nested_proto_param in nested_proto_group.params:
                                nested_kind = codegen_ir.TemplateParamKind(
                                    nested_proto_param.kind.name.removeprefix(
                                        "TEMPLATE_PARAM_KIND_").title())

                                nested_type_expr = conv_proto_type(
                                    nested_proto_param.type_expr)

                                nested_default_value = None
                                if nested_proto_param.default:
                                    nested_default_value = conv_proto_type(
                                        nested_proto_param.default[0])

                                nested_group.Params.append(
                                    codegen_ir.GenTuTemplateTypename(
                                        Kind=nested_kind,
                                        TypeExpr=nested_type_expr,
                                        Variadic=nested_proto_param.variadic,
                                        Concept=nested_proto_param.concept or None,
                                        Default=nested_default_value,
                                        TemplateParams=None,
                                    ))

                            nested_template_params.Stacks.append(nested_group)

                group.Params.append(
                    codegen_ir.GenTuTemplateTypename(
                        Kind=kind,
                        TypeExpr=type_expr,
                        Variadic=proto_param.variadic,
                        Concept=proto_param.concept or None,
                        Default=default_value,
                        TemplateParams=nested_template_params,
                    ))

            TemplateParams.Stacks.append(group)

    return TemplateParams


@beartype
def conv_proto_record(record: pb.Record,
                      original: Optional[Path]) -> codegen_ir.GenTuStruct:
    "Convert reflection tool protobuf record to codgen IR struct"
    result = codegen_ir.GenTuStruct(
        conv_proto_type(record.name, is_anon_name=not record.has_name),
        codegen_ir.GenTuDoc(""),
    )

    with ExceptionContextNote(f"{result.Name}"):
        result.ReflectionParams = conv_proto_reflection_params(record.reflection_params)

    result.IsExplicitInstantiation = record.is_explicit_instantiation
    result.IsTemplateRecord = record.is_template_record
    result.OriginalPath = copy(original)
    result.IsForwardDecl = record.is_forward_decl
    result.IsAbstract = record.is_abstract
    result.HasName = record.has_name
    result.IsDescribedRecord = record.is_described_record

    for arg in record.explicit_template_params:
        result.ExplicitTemplateParams.append(conv_proto_type(arg))

    if result.IsTemplateRecord:
        result.TemplateParams = conv_proto_templates(record.templates)

    for _field in record.fields:
        if _field.is_type_decl:
            result.Fields.append(
                codegen_ir.GenTuField(
                    Type=None,
                    Name=_field.name,
                    Doc=conv_doc_comment(_field.doc),
                    IsTypeDecl=True,
                    Decl=conv_proto_record(_field.type_decl, original),
                    OriginName="refl",
                ))

        else:
            result.Fields.append(
                codegen_ir.GenTuField(
                    Type=conv_proto_type(_field.type),
                    Name=_field.name,
                    Doc=conv_doc_comment(_field.doc),
                    OriginName="refl",
                ))

    for base in record.bases:
        result.Bases.append(conv_proto_type(base.name))

    for meth in record.methods:
        IsConstructor = meth.kind in [
            pb.RecordMethodKind.ConvertingConstructor,
            pb.RecordMethodKind.MoveConstructor,
            pb.RecordMethodKind.DefaultConstructor,
            pb.RecordMethodKind.CopyConstructor,
        ]

        if IsConstructor:
            if result.IsExplicitInstantiation:
                final_result = result.Name.copy_update(
                    Params=result.ExplicitTemplateParams)
            else:
                final_result = result.Name
        else:
            final_result = conv_proto_type(meth.return_ty)

        func = codegen_ir.GenTuFunction(
            ReturnType=final_result,
            Name=meth.name,
            Doc=conv_doc_comment(meth.doc),
            IsConst=meth.is_const,
            IsStatic=meth.is_static,
            OriginalPath=original,
            Args=[conv_proto_arg(arg) for arg in meth.args],
            ParentClass=result.declarationQualName(),
            OriginName="refl",
            IsConstructor=IsConstructor,
            IsVirtual=meth.is_virtual,
            IsPureVirtual=meth.is_pure_virtual,
        )

        with ExceptionContextNote(f"{result.Name}::{func.Name}"):
            func.ReflectionParams = conv_proto_reflection_params(meth.reflection_params)

        result.Methods.append(func)

    for record in record.nested_rec:
        result.Nested.append(conv_proto_record(record, original))

    for _enum in record.nested_enum:
        result.Nested.append(conv_proto_enum(_enum, original))

    return result


@beartype
def conv_proto_enum(en: pb.Enum, original: Optional[Path]) -> codegen_ir.GenTuEnum:
    result = codegen_ir.GenTuEnum(conv_proto_type(en.name), codegen_ir.GenTuDoc(""), [])
    result.IsForwardDecl = en.is_forward_decl
    result.OriginalPath = copy(original)
    result.IsDescribedEnum = en.is_described_enum
    for _field in en.fields:
        result.Fields.append(
            codegen_ir.GenTuEnumField(
                _field.name,
                codegen_ir.GenTuDoc(""),
                Value=_field.value,
                OriginName="refl",
            ))

    with ExceptionContextNote(f"{result.Name}"):
        result.ReflectionParams = conv_proto_reflection_params(en.reflection_params)

    return result


@beartype
def conv_proto_arg(arg: pb.Arg) -> codegen_ir.GenTuIdent:
    return codegen_ir.GenTuIdent(
        Name=arg.name,
        Type=conv_proto_type(arg.type),
        Value=conv_proto_default(arg.default),
        OriginName="refl",
    )


@beartype
def conv_proto_function(rec: pb.Function,
                        original: Optional[Path]) -> codegen_ir.GenTuFunction:
    result = codegen_ir.GenTuFunction(
        ReturnType=conv_proto_type(rec.result_ty),
        Name=rec.name,
        Args=[conv_proto_arg(arg) for arg in rec.arguments],
        Doc=codegen_ir.GenTuDoc(""),
        OriginalPath=copy(original),
        Spaces=[conv_proto_type(T) for T in rec.spaces],
        OriginName="refl",
    )

    with ExceptionContextNote(f"{result.Name}"):
        result.ReflectionParams = conv_proto_reflection_params(rec.reflection_params)

    return result


@beartype
def conv_proto_typedef(rec: pb.Typedef,
                       original: Optional[Path]) -> codegen_ir.GenTuTypedef:
    return codegen_ir.GenTuTypedef(
        Name=conv_proto_type(rec.name),
        Base=conv_proto_type(rec.base_type),
        Original=original,
        OriginName="refl",
    )


@beartype
def conv_proto_include(rec: pb.Include,
                       original: Optional[Path]) -> codegen_ir.GenTuInclude:
    return codegen_ir.GenTuInclude(
        what=rec.relative_path,
        absolutePath=rec.absolute_path,
    )


@beartype
@dataclass
class ConvTu:
    structs: List[codegen_ir.GenTuStruct] = field(default_factory=list)
    functions: List[codegen_ir.GenTuFunction] = field(default_factory=list)
    enums: List[codegen_ir.GenTuEnum] = field(default_factory=list)
    typedefs: List[codegen_ir.GenTuTypedef] = field(default_factory=list)
    includes: List[codegen_ir.GenTuInclude] = field(default_factory=list)
    absoluteOriginal: Optional[str] = None

    def get_all(self) -> List[codegen_ir.GenTuUnion]:
        return self.enums + self.typedefs + self.structs + self.functions


from dataclasses import fields, is_dataclass, MISSING
from typing import Any, get_args, get_origin, get_type_hints, Union


def dict_to_dataclass(
    data: Any,
    cls: type[Any],
    allow_extra_fields: set[tuple[type, str]],
) -> Any:

    def format_path(path: tuple[Any, ...]) -> str:
        if not path:
            return "$"

        result = "$"
        for part in path:
            if isinstance(part, int):
                result += f"[{part}]"
            else:
                result += f".{part}"
        return result

    def aux_impl(data: Any, cls: type[Any], path: tuple[Any, ...]) -> Any:
        if data is None:
            return None

        elif cls == pb_google.Struct:
            return pb_google.Struct.from_dict(data)

        origin = get_origin(cls)

        if origin is Union:
            args = [arg for arg in get_args(cls) if arg is not type(None)]
            for arg in args:
                try:
                    return aux(data, arg, path)
                except Exception:
                    pass
            return data

        if origin is list:
            (item_type,) = get_args(cls)
            return [
                aux(item, item_type, path + (index,)) for index, item in enumerate(data)
            ]

        if origin is tuple:
            item_types = get_args(cls)
            if len(item_types) == 2 and item_types[1] is Ellipsis:
                return tuple(
                    aux(item, item_types[0], path + (index,))
                    for index, item in enumerate(data))
            return tuple(
                aux(item, item_type, path + (index,))
                for index, (item, item_type) in enumerate(zip(data, item_types)))

        if origin is dict:
            key_type, value_type = get_args(cls)
            return {
                aux(key, key_type, path + (f"<key:{key}>",)):
                    aux(value, value_type, path + (key,)) for key, value in data.items()
            }

        if is_dataclass(cls):
            if not isinstance(data, dict):
                raise TypeError(
                    f"At {format_path(path)}: expected dict for {cls.__name__}, got {type(data).__name__}"
                )

            cls_fields = fields(cls)
            field_names = {field.name for field in cls_fields}
            unknown_fields = [
                f for f in set(data) - field_names if (cls, f) not in allow_extra_fields
            ]
            if unknown_fields:
                raise KeyError(
                    f"At {format_path(path)}: unknown fields for {cls.__module__}.{cls.__name__}: "
                    f"{sorted(unknown_fields)}, has fields {field_names}")

            type_hints = get_type_hints(cls)
            kwargs = {}

            for field in cls_fields:
                field_path = path + (field.name,)
                if field.name not in data:
                    if field.default is not MISSING or field.default_factory is not MISSING:
                        continue
                    raise KeyError(
                        f"At {format_path(field_path)}: missing required field")

                field_type = type_hints[field.name]
                kwargs[field.name] = aux(data[field.name], field_type, field_path)

            return cls(**kwargs)

        elif issubclass(cls, (enum.Enum, betterproto.Enum)):
            return cls[data]

        return data

    def aux(data: Any, cls: type[Any], path: tuple[Any, ...]) -> Any:
        try:
            return aux_impl(data, cls, path)

        except Exception as e:
            e.add_note(f"cls: {cls.__module__}.{cls.__name__}")
            raise e from None

    return aux(data, cls, ())


@beartype
def open_proto_file(path: Path) -> pb.Tu:
    unit = pb.Tu()
    assert path.exists(), f"Reflection file {path} does not exist"

    with ExceptionContextNote(f"Parsing file {path}"):
        if path.suffix == ".json":
            import commentjson
            unit = dict_to_dataclass(
                commentjson.loads(path.read_text()),
                pb.Tu,
                allow_extra_fields={
                    (pb.Tu, "$schema"),
                },
            )

        else:
            with open(path, "rb") as f:
                unit = pb.Tu.FromString(f.read())

    return unit


@beartype
def conv_proto_file(path: Path, original: Optional[Path] = None) -> ConvTu:
    unit = open_proto_file(path)
    return ConvTu(
        absoluteOriginal=unit.absolute_path,
        structs=[conv_proto_record(rec, original) for rec in unit.records],
        enums=[conv_proto_enum(rec, original) for rec in unit.enums],
        typedefs=[conv_proto_typedef(rec, original) for rec in unit.typedefs],
        functions=[conv_proto_function(rec, original) for rec in unit.functions],
        includes=[conv_proto_include(rec, original) for rec in unit.includes],
    )
