"""
Reading protobuf files generated by the reflection tool.
"""

from copy import copy
import json
from pathlib import Path
import re

from beartype import beartype
from py_codegen.codegen_ir import *
import py_codegen.proto_lib.reflection_defs as pb
from py_scriptutils.script_logging import log

CAT = __name__


@beartype
def conv_proto_default(value: pb.Expr) -> Optional[str]:
    if value.kind == pb.ExprKind.Lit and 0 < len(value.value):
        return value.value

    else:
        return None


@beartype
def strip_comment_prefixes(comment: str) -> List[str]:

    def drop_leading(prefix: re.Pattern, text: str) -> List[str]:
        result: List[str] = []
        for line in text.strip().splitlines():
            result.append(re.sub(prefix, "", line))

        return result

    # Identify and strip comment markers, then delegate to process_content
    if comment.startswith("///") or comment.startswith("//!"):
        return drop_leading(re.compile("///?<?!?\\s*"), comment)
    elif comment.startswith("/**") or comment.startswith("/*!"):
        # Removing the leading /** or /*! and trailing */
        content = comment[3:-2].strip()
        # Remove any '*' prefixes that might exist on each line
        content = "\n".join(line.strip().lstrip("* ") for line in content.splitlines())
        return content.splitlines()
    elif comment.startswith("//"):
        return comment[2:].splitlines()
    elif comment.startswith("/*"):
        # Removing the leading /* and potential trailing */
        content = comment[2:]
        if content.endswith("*/"):
            content = content[:-2]
        content = "\n".join(line.strip().lstrip("* ") for line in content.splitlines())
        return content.splitlines()
    else:
        raise ValueError(f"Unrecognized comment style: {comment}")


@beartype
def conv_doc_comment(comment: str) -> GenTuDoc:
    if not comment:
        return GenTuDoc("")

    # Helper function to process content after stripping comment markers
    def process_content(content: List[str]) -> GenTuDoc:
        brief, full = [], []
        is_brief = True

        for line in content:
            line = line.strip()
            if not line:
                is_brief = False
                continue

            if is_brief:
                brief.append(line)
            else:
                full.append(line)

        return GenTuDoc("\n".join(brief), "\n".join(full))

    return process_content(strip_comment_prefixes(comment))


@beartype
def conv_proto_type(typ: pb.QualType, is_anon_name: bool = False) -> QualType:
    res: QualType = QualType(Name=typ.name)
    res.DbgOrigin = typ.dbg_origin

    for space in typ.spaces:
        res.Spaces.append(conv_proto_type(space))

    match typ.kind:
        case pb.TypeKind.RegularType:
            res.IsBuiltin = typ.is_builtin
            for param in typ.parameters:
                res.Params.append(conv_proto_type(param))

            # if not is_anon_name:
            #     assert res.name != "", typ

        case pb.TypeKind.FunctionPtr:
            res.Kind = QualTypeKind.FunctionPtr
            res.Func = QualType.Function(
                ReturnType=conv_proto_type(typ.parameters[0]),
                Args=[conv_proto_type(Arg) for Arg in typ.parameters[1:]]
                if 1 < len(typ.parameters) else [])

        case pb.TypeKind.Array:
            res.Kind = QualTypeKind.Array
            res.Params = [conv_proto_type(t) for t in typ.parameters]

        case pb.TypeKind.TypeExpr:
            res.Kind = QualTypeKind.TypeExpr
            res.Expr = typ.type_value.value

    res.IsConst = any([it.is_const for it in typ.qualifiers])
    res.IsNamespace = typ.is_namespace
    res.IsGlobalNamespace = typ.is_global_namespace
    res.RefKind = {
        pb.ReferenceKind.NotRef: ReferenceKind.NotRef,
        pb.ReferenceKind.LValue: ReferenceKind.LValue,
        pb.ReferenceKind.RValue: ReferenceKind.RValue,
    }[typ.ref_kind]

    res.IsTemplateTypeParam = typ.is_template_type_param
    res.IsTemplateInjectedType = typ.is_template_injected_type

    res.PtrCount = len([it for it in typ.qualifiers if it.is_pointer])

    return res


@beartype
def conv_proto_record(record: pb.Record, original: Optional[Path]) -> GenTuStruct:
    "Convert reflection tool protobuf record to codgen IR struct"
    result = GenTuStruct(
        conv_proto_type(record.name, is_anon_name=not record.has_name),
        GenTuDoc(""),
    )

    if record.reflection_params:
        try:
            result.ReflectionParams = GenTuReflParams.model_validate_json(
                record.reflection_params)

        except json.JSONDecodeError as e:
            e.add_note(f"While parsing reflection parameters for {result.Name.format()}")
            e.add_note(f"Original text is '{record.reflection_params}'")

            raise e from None

    result.IsExplicitInstantiation = record.is_explicit_instantiation
    result.IsTemplateRecord = record.is_template_record
    result.OriginalPath = copy(original)
    result.IsForwardDecl = record.is_forward_decl
    result.IsAbstract = record.is_abstract
    result.HasName = record.has_name
    result.IsDescribedRecord = record.is_described_record

    for arg in record.explicit_template_params:
        result.ExplicitTemplateParams.append(conv_proto_type(arg))

    if result.IsTemplateRecord:
        result.TemplateParams = GenTuTemplateParams(Stacks=[])
        for _template in record.templates:
            group = GenTuTemplateGroup()
            for _param in _template.parameters:
                group.Params.append(
                    GenTuTemplateTypename(
                        Variadic=_param.is_variadic,
                        Placeholder=_param.is_placeholder,
                        Name=_param.name,
                        Concept=_param.concept,
                    ))

            result.TemplateParams.Stacks.append(group)

    for _field in record.fields:
        if _field.is_type_decl:
            result.Fields.append(
                GenTuField(
                    Type=None,
                    Name=_field.name,
                    Doc=conv_doc_comment(_field.doc),
                    IsTypeDecl=True,
                    Decl=conv_proto_record(_field.type_decl, original),
                    OriginName="refl",
                ))

        else:
            result.Fields.append(
                GenTuField(
                    Type=conv_proto_type(_field.type),
                    Name=_field.name,
                    Doc=conv_doc_comment(_field.doc),
                    OriginName="refl",
                ))

    for base in record.bases:
        result.Bases.append(conv_proto_type(base.name))

    for meth in record.methods:
        # if meth.kind != pb.RecordMethodKind.Base:
        #     continue

        IsConstructor = meth.kind in [
            pb.RecordMethodKind.ConvertingConstructor,
            pb.RecordMethodKind.MoveConstructor,
            pb.RecordMethodKind.DefaultConstructor,
            pb.RecordMethodKind.CopyConstructor,
        ]

        if IsConstructor:
            if result.IsExplicitInstantiation:
                final_result = result.Name.copy_update(
                    Params=result.ExplicitTemplateParams)
            else:
                final_result = result.Name
        else:
            final_result = conv_proto_type(meth.return_ty)

        func = GenTuFunction(
            ReturnType=final_result,
            Name=meth.name,
            Doc=conv_doc_comment(meth.doc),
            IsConst=meth.is_const,
            IsStatic=meth.is_static,
            OriginalPath=original,
            Args=[conv_proto_arg(arg) for arg in meth.args],
            ParentClass=result,
            OriginName="refl",
            IsConstructor=IsConstructor,
            IsVirtual=meth.is_virtual,
            IsPureVirtual=meth.is_pure_virtual,
        )

        if meth.reflection_params:
            func.ReflectionParams = GenTuReflParams.model_validate_json(
                meth.reflection_params)

        result.Methods.append(func)

    for record in record.nested_rec:
        result.Nested.append(conv_proto_record(record, original))

    for _enum in record.nested_enum:
        result.Nested.append(conv_proto_enum(_enum, original))

    return result


@beartype
def conv_proto_enum(en: pb.Enum, original: Optional[Path]) -> GenTuEnum:
    result = GenTuEnum(conv_proto_type(en.name), GenTuDoc(""), [])
    result.IsForwardDecl = en.is_forward_decl
    result.OriginalPath = copy(original)
    result.IsDescribedEnum = en.is_described_enum
    for _field in en.fields:
        result.Fields.append(
            GenTuEnumField(
                _field.name,
                GenTuDoc(""),
                Value=_field.value,
                OriginName="refl",
            ))

    if en.reflection_params:
        result.ReflectionParams = GenTuReflParams.model_validate_json(
            en.reflection_params)

    return result


@beartype
def conv_proto_arg(arg: pb.Arg) -> GenTuIdent:
    return GenTuIdent(
        Name=arg.name,
        Type=conv_proto_type(arg.type),
        Value=conv_proto_default(arg.default),
        OriginName="refl",
    )


@beartype
def conv_proto_function(rec: pb.Function, original: Optional[Path]) -> GenTuFunction:
    result = GenTuFunction(
        ReturnType=conv_proto_type(rec.result_ty),
        Name=rec.name,
        Args=[conv_proto_arg(arg) for arg in rec.arguments],
        Doc=GenTuDoc(""),
        OriginalPath=copy(original),
        Spaces=[conv_proto_type(T) for T in rec.spaces],
        OriginName="refl",
    )

    if rec.reflection_params:
        result.ReflectionParams = GenTuReflParams.model_validate_json(
            rec.reflection_params)

    return result


@beartype
def conv_proto_typedef(rec: pb.Typedef, original: Optional[Path]) -> GenTuTypedef:
    return GenTuTypedef(
        Name=conv_proto_type(rec.name),
        Base=conv_proto_type(rec.base_type),
        Original=original,
        OriginName="refl",
    )


@beartype
def conv_proto_include(rec: pb.Include, original: Optional[Path]) -> GenTuInclude:
    return GenTuInclude(
        what=rec.relative_path,
        absolutePath=rec.absolute_path,
    )


@beartype
@dataclass
class ConvTu:
    structs: List[GenTuStruct] = field(default_factory=list)
    functions: List[GenTuFunction] = field(default_factory=list)
    enums: List[GenTuEnum] = field(default_factory=list)
    typedefs: List[GenTuTypedef] = field(default_factory=list)
    includes: List[GenTuInclude] = field(default_factory=list)
    absoluteOriginal: Optional[str] = None

    def get_all(self) -> List[GenTuUnion]:
        return self.enums + self.typedefs + self.structs + self.functions


@beartype
def open_proto_file(path: Path) -> pb.TU:
    unit = pb.TU()
    assert path.exists(), f"Reflection file {path} does not exist"

    with open(path, "rb") as f:
        unit = pb.TU.FromString(f.read())

    return unit


@beartype
def conv_proto_file(path: Path, original: Optional[Path] = None) -> ConvTu:
    unit = open_proto_file(path)
    return ConvTu(
        absoluteOriginal=unit.absolute_path,
        structs=[conv_proto_record(rec, original) for rec in unit.records],
        enums=[conv_proto_enum(rec, original) for rec in unit.enums],
        typedefs=[conv_proto_typedef(rec, original) for rec in unit.typedefs],
        functions=[conv_proto_function(rec, original) for rec in unit.functions],
        includes=[conv_proto_include(rec, original) for rec in unit.includes],
    )
