[project]
name = "ex_cpp_binary_pytest_package"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "pytest>=8.4.2",
  "ex_py_standalone",
]

[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ex_cpp_binary_pytest_package"]

[tool.uv.sources]
ex_py_standalone = { workspace = true }

[tool.pytest.ini_options]
testpaths = ["."]
