exclude: |
  (?x)^(
    src/wrappers/c/haxorg_c\.h|
    src/wrappers/c/haxorg_c\.cpp|
    src/wrappers/c/haxorg_c_vtables\.hpp|
    src/wrappers/c/haxorg_c_vtables\.cpp|
    src/wrappers/js/haxorg_wasm\.cpp|
    src/wrappers/js/haxorg_wasm_types\.d\.ts|
    src/wrappers/js/haxorg_c\.cpp|
    src/wrappers/js/haxorg_c\.h|
    scripts/py_haxorg/py_haxorg/pyhaxorg\.pyi|
    src/py_libs/pyhaxorg/pyhaxorg\.cpp|
    src/haxorg/serde/SemOrgProto\.proto|
    src/haxorg/serde/SemOrgSerdeDeclarations\.hpp|
    src/haxorg/serde/SemOrgSerdeDefinitions\.cpp|
    src/haxorg/exporters/Exporter\.tcc|
    src/haxorg/imm/ImmOrgSerde\.tcc|
    src/haxorg/imm/ImmOrgAdapterGenerated\.hpp|
    src/haxorg/imm/ImmOrgAdapterGenerated\.cpp|
    src/haxorg/exporters/ExporterMethods\.tcc|
    src/haxorg/sem/SemOrgEnums\.hpp|
    src/haxorg/sem/SemOrgEnums\.cpp|
    src/haxorg/sem/SemOrgSharedTypes\.hpp|
    src/haxorg/sem/SemOrgTypes\.hpp|
    src/haxorg/imm/ImmOrgTypes\.hpp
  )$
repos:
  - repo: local
    hooks:
      - id: pre-commit-sg-rewrite
        name: Remove and unify code styles
        language: system
        entry: ast-grep scan --color=never -c repo_py_validate/sgconfig.yaml scripts/cxx_repository/code_forensics.cpp -U
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        exclude: ^\.clang-format$
  - repo: local
    hooks:
      - id: isort
        name: Format python imports
        entry: uv run --dev isort
        language: system
        types: [python]
        stages: [manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        name: ruff fix imports
        # I: sort and organize imports
        # F401: remove unused impots
        # UP035: import Sequence/Mapping from collections.abc instead of the typing
        args: [--fix, "--select=I,I001,F401,UP035", "--fixable=I,I001,F401,UP035"]

      - id: ruff-format

      - id: ruff-check
        name: ruff validate
        stages: [manual]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        types_or: [c, c++, cuda]
  - repo: local
    hooks:
      - id: check-repo-tasks
        name: check-repo-tasks
        entry: uv run --dev ./scripts/py_repository/py_repository/repo_hooks/validate_repo_task_config.py
        language: system
        files: ^scripts/py_repository/py_repository/repo_tasks/.*\.json$
        stages: [manual]
  - repo: local
    hooks:
      - id: find-debug-calls
        name: Find debug calls
        entry: uv run --dev ./scripts/py_repository/py_repository/repo_hooks/validate_cxx_code.py
        language: system
        types: [c++]
        stages: [manual]
  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: 0.29.1
    hooks:
    - id: gersemi
  - repo: local
    hooks:
      - id: no-undocumented-api
        name: Prevent undocumented Python/C++ functions/classes
        entry: uv run --dev ./scripts/py_repository/py_repository/repo_hooks/validate_documentation_changes.py
        language: system
        pass_filenames: true
        files: \.(py|h|hh|hpp|hxx|c|cc|cpp|cxx)$
        stages: [manual]
