version: 3

vars:
  REL_CONAN: "build/dependencies/conan"
  CONAN_DIR: |
    {{env "PWD"}}/build/dependencies/conan
  LLVM_DIR: |
    {{env "PWD"}}/toolchain/llvm

tasks:
  run:
    dir: "{{.DIR}}"
    cmds:
      - >
        {{.IN}}
        {{.ARGS}}

  debug:
    dir: "{{.DIR}}"
    env:
      IN_PWD: "{{.PWD}}"
      IN: "{{.IN}}"
      ARGS: "{{.ARGS}}"
    cmds:
      - bash +x {{.PWD}}/scripts/debug_run.sh

  missing_docs:
    cmds:
      - >
        doxygen Doxyfile 2>&1 |
        rg --line-buffered warning |
        grep --line-buffered -v "not declared or defined"

  llvm_profdata:
    dir: "{{.DIR}}"
    cmds:
      # Unclutter program output, save command execution to separate file
      - llvm-profdata merge -sparse *.profraw -o coverage.profdata > profdata_output.txt
      - llvm-cov show {{.BINARY}} -instr-profile=coverage.profdata -format=html > coverage.html
      - llvm-cov export -format=lcov -instr-profile=coverage.profdata {{.BINARY}} > coverage.lcov
      - llvm-cov export -format=text -instr-profile=coverage.profdata {{.BINARY}} > coverage.json
      - genhtml -o html coverage.lcov > genhtml_output.txt


  conan_remove:
    vars:
      REL_PROFILE: "{{.PWD}}/conanprofile.txt"
    cmds:
      - >
        conan
        remove '*' --force

  conan_install:
    vars:
      REL_PROFILE: "{{.PWD}}/conanprofile.txt"
    cmds:
      - >
        conan
        install
        .
        --install-folder {{.REL_CONAN}}
        --build=missing
        --profile {{.REL_PROFILE}}

    # status:
    #   - test -e {{.CONAN_DIR}}

  
  tests:
    desc: "Compile and run tests"
    dir: build
    deps: [conan_install]
    env:
      CLICOLOR_FORCE: 1
      GENERATOR: Ninja
    cmds:
      # - rm -rf *
      # - cmake -DCMAKE_BUILD_TYPE=Debug -GNinja --log-level=TRACE ..
        # -GNinja
      - killall tests.bin || true
      - >
        cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DUSE_SINGLE_FILE_CATCH=ON
        -DCMAKE_CXX_COMPILER=clang++
        -DTEST_COVERAGE=ON
        -DMAX_COMPILE_ERRORS=1
        --log-level=TRACE
        ..

      # - make -j8 2> /tmp/compile.txt
      - make -j8 2> /tmp/compile.txt
      # - ninja -v -d explain
      # - "{{.PWD}}/build/bin/tests.bin"
      # - task: perf_run
      #   vars:
      #     DIR: "{{.PWD}}/build"
      #     IN: "{{.PWD}}/build/bin/tests.bin"

      - task: debug
        vars:
          DIR: "{{.PWD}}/build"
          IN: "{{.PWD}}/build/bin/tests.bin"
          # ARGS: >
          #   [notes]
          #   --corpus-glob
          #   *list.yaml

      # - task: debug
      #   vars:
      #     DIR: "{{.PWD}}/build"
      #     IN: "{{.PWD}}/build/bin/tests.bin"

      - task: llvm_profdata
        vars:
          DIR: "{{.PWD}}/build"
          BINARY: "{{.PWD}}/build/bin/tests.bin"

  perf_run:
    dir: "{{.DIR}}"
    cmds:
      - "perf record {{.IN}}"
