version: 3

tasks:
  tests:
    desc: "Compile and run tests"
    dir: build
    env:
      CLICOLOR_FORCE: 1
    cmds:
      - cmake --log-level=TRACE ..
      - make -j8
      - ../tests.bin
      # - cmake -GNinja ..
      # - ninja -v

  plantuml:
    desc: "Compile and test plantuml grammar"
    cmds:
      - xmake build --verbose --warning --yes plantuml_parser
