version: 3

tasks:
  tests:
    desc: "Compile and run tests"
    dir: build
    env:
      CLICOLOR_FORCE: 1
    cmds:
      # - rm -rf *
      # - cmake -DCMAKE_BUILD_TYPE=Debug -GNinja --log-level=TRACE ..
      - cmake -DCMAKE_BUILD_TYPE=Debug --log-level=TRACE ..
      - make -j8
      # - ninja -v
      - ../tests.bin

  plantuml:
    desc: "Compile and test plantuml grammar"
    cmds:
      - xmake build --verbose --warning --yes plantuml_parser
