version: 3

vars:
  REL_CONAN: "build/dependencies/conan"
  CONAN_DIR: |
    {{env "PWD"}}/build/dependencies/conan

tasks:
  run:
    dir: "{{.DIR}}"
    cmds:
      - >
        {{.IN}}
        {{.ARGS}}

  debug:
    dir: "{{.DIR}}"
    env:
      IN_PWD: "{{.PWD}}"
      IN: "{{.IN}}"
      ARGS: "{{.ARGS}}"
    cmds:
      - bash +x {{.PWD}}/scripts/debug_run.sh

  llvm_profdata:
    dir: "{{.DIR}}"
    cmds:
      # Unclutter program output, save command execution to separate file
      - llvm-profdata merge -sparse *.profraw -o coverage.profdata > profdata_output.txt
      - llvm-cov show {{.BINARY}} -instr-profile=coverage.profdata -format=html > coverage.html
      - llvm-cov export -format=lcov -instr-profile=coverage.profdata {{.BINARY}} > coverage.lcov
      - llvm-cov export -format=text -instr-profile=coverage.profdata {{.BINARY}} > coverage.json
      - genhtml -o html coverage.lcov > genhtml_output.txt

  conan_install:
    cmds:
      - >
        conan
        install
        .
        -if {{.REL_CONAN}}
        --build=missing
        --settings compiler.version=15
        --settings compiler=clang

    # status:
    #   - test -e {{.CONAN_DIR}}

  
  tests:
    desc: "Compile and run tests"
    dir: build
    deps: [conan_install]
    env:
      CLICOLOR_FORCE: 1
      GENERATOR: Ninja
    cmds:
      # - rm -rf *
      # - cmake -DCMAKE_BUILD_TYPE=Debug -GNinja --log-level=TRACE ..
        # -GNinja
      - >
        cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DUSE_SINGLE_FILE_CATCH=ON
        -DCMAKE_CXX_COMPILER=clang++
        -DTEST_COVERAGE=ON
        --log-level=TRACE
        ..

      - make -j8
      # - ninja -v -d explain
      - task: debug
        vars:
          DIR: "{{.PWD}}/build"
          IN: "{{.PWD}}/build/bin/tests.bin"

      # - task: debug
      #   vars:
      #     DIR: "{{.PWD}}/build"
      #     IN: "{{.PWD}}/build/bin/tests.bin"

      - task: llvm_profdata
        vars:
          DIR: "{{.PWD}}/build"
          BINARY: "{{.PWD}}/build/bin/tests.bin"

  plantuml:
    desc: "Compile and test plantuml grammar"
    cmds:
      - xmake build --verbose --warning --yes plantuml_parser
