version: 3

tasks:
  tests:
    desc: "Compile and run tests"
    cmds:
      - xmake config -m debug
      - xmake build --warning --yes test

  plantuml:
    desc: "Compile and test plantuml grammar"
    cmds:
      - xmake build --verbose --warning --yes plantuml_parser
