from typing import *
from enum import Enum
from datetime import datetime, date, time

T = TypeVar("T")

class ImmBox[T]():
    def get(self) -> T: ...

class ImmFlexVector[T]():
    def at(self, idx: int) -> T: ...
    def __len__(self) -> int: ...

class ImmVector[T]():
    def at(self, idx: int) -> T: ...
    def __len__(self) -> int: ...

class ImmAdapterTBase[T](ImmAdapter):
    pass

class GraphDimension(Enum):
    XDIM = 1
    YDIM = 2
    UNSET = 3

class GraphNodeConstraintKind(Enum):
    Empty = 1
    Align = 2
    FixedRelative = 3
    Separate = 4
    MultiSeparate = 5
    PageBoundary = 6

class GraphEdgeConstraintPort(Enum):
    Default = 1
    North = 2
    South = 3
    West = 4
    East = 5
    Center = 6

class GraphPoint:
    def __init__(self, x: double, y: double) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    x: double
    y: double

class GraphPath:
    def __init__(self, points: List, startPoint: Optional, endPoint: Optional, bezier: bool) -> None: ...
    @overload
    def point(self, x: double, y: double) -> None: ...
    @overload
    def point(self, p: GraphPoint) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    points: List
    startPoint: Optional
    endPoint: Optional
    bezier: bool

class GraphSize:
    def __init__(self, w: double, h: double) -> None: ...
    def height(self) -> double: ...
    def width(self) -> double: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    w: double
    h: double

class GraphRect:
    def __init__(self, left: double, top: double, width: double, height: double) -> None: ...
    def size(self) -> GraphSize: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    left: double
    top: double
    width: double
    height: double

class GraphNodeConstraintEmpty:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...

class GraphNodeConstraintAlignSpec:
    def __init__(self, node: int, fixPos: Optional, offset: double) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    node: int
    fixPos: Optional
    offset: double

class GraphNodeConstraintAlign:
    def __init__(self, nodes: List, dimension: GraphDimension) -> None: ...
    def toColaString(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    nodes: List
    dimension: GraphDimension

class GraphNodeConstraintSeparate:
    def __init__(self, left: GraphNodeConstraintAlign, right: GraphNodeConstraintAlign, separationDistance: double, isExactSeparation: bool, dimension: GraphDimension) -> None: ...
    def toColaString(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    left: GraphNodeConstraintAlign
    right: GraphNodeConstraintAlign
    separationDistance: double
    isExactSeparation: bool
    dimension: GraphDimension

class GraphNodeConstraintMultiSeparate:
    def __init__(self, lines: List, alignPairs: List, dimension: GraphDimension, separationDistance: double, isExactSeparation: bool) -> None: ...
    def toColaString(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    lines: List
    alignPairs: List
    dimension: GraphDimension
    separationDistance: double
    isExactSeparation: bool

class GraphNodeConstraintFixedRelative:
    def __init__(self, nodes: List, fixedPosition: bool) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    nodes: List
    fixedPosition: bool

class GraphNodeConstraintPageBoundary:
    def __init__(self, rect: GraphRect, weight: double, nodes: List) -> None: ...
    def toColaString(self, allRects: stdvector) -> str: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    rect: GraphRect
    weight: double
    nodes: List

class GraphNodeConstraint:
    def __init__(self) -> None: ...
    def getEmpty(self) -> GraphNodeConstraintEmpty: ...
    def isEmpty(self) -> bool: ...
    def getAlign(self) -> GraphNodeConstraintAlign: ...
    def isAlign(self) -> bool: ...
    def getFixedRelative(self) -> GraphNodeConstraintFixedRelative: ...
    def isFixedRelative(self) -> bool: ...
    def getSeparate(self) -> GraphNodeConstraintSeparate: ...
    def isSeparate(self) -> bool: ...
    def getMultiSeparate(self) -> GraphNodeConstraintMultiSeparate: ...
    def isMultiSeparate(self) -> bool: ...
    def getPageBoundary(self) -> GraphNodeConstraintPageBoundary: ...
    def isPageBoundary(self) -> bool: ...
    def getKind(self) -> GraphNodeConstraintKind: ...
    @staticmethod
    def InitEmptyStatic(self, arg: GraphNodeConstraintEmpty) -> GraphNodeConstraint: ...
    @staticmethod
    def InitAlignStatic(self, arg: GraphNodeConstraintAlign) -> GraphNodeConstraint: ...
    @staticmethod
    def InitSeparateStatic(self, arg: GraphNodeConstraintSeparate) -> GraphNodeConstraint: ...
    @staticmethod
    def InitMultiSeparateStatic(self, arg: GraphNodeConstraintMultiSeparate) -> GraphNodeConstraint: ...
    @staticmethod
    def InitFixedRelativeStatic(self, arg: GraphNodeConstraintFixedRelative) -> GraphNodeConstraint: ...
    @staticmethod
    def InitPageBoundaryStatic(self, arg: GraphNodeConstraintPageBoundary) -> GraphNodeConstraint: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...

class GraphEdge:
    def __init__(self, source: int, target: int, bundle: int) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    source: int
    target: int
    bundle: int

class GraphEdgeConstraint:
    def __init__(self, sourcePort: GraphEdgeConstraintPort, targetPort: GraphEdgeConstraintPort, sourceOffset: Optional, targetOffset: Optional, sourceCheckpoint: Optional, targetCheckpoint: Optional) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    sourcePort: GraphEdgeConstraintPort
    targetPort: GraphEdgeConstraintPort
    sourceOffset: Optional
    targetOffset: Optional
    sourceCheckpoint: Optional
    targetCheckpoint: Optional

class GraphLayoutIRSubgraph:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...

class GraphLayoutIREdge:
    def __init__(self, paths: List, labelRect: Optional) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    paths: List
    labelRect: Optional

class GraphLayoutIRResultSubgraph:
    def __init__(self, bbox: GraphRect, subgraphs: List) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    bbox: GraphRect
    subgraphs: List

class GraphLayoutIRResult:
    def __init__(self, fixed: List, lines: Dict, bbox: GraphRect, subgraphs: List, subgraphPaths: List) -> None: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    fixed: List
    lines: Dict
    bbox: GraphRect
    subgraphs: List
    subgraphPaths: List

class GraphLayoutIR:
    def __init__(self, rectangles: List, edges: List, nodeConstraints: List, subgraphs: List, edgeLabels: Dict, edgeConstraints: Dict, width: double, height: double, leftBBoxMargin: double, rightBBoxMargin: double, topBBoxMargin: double, bottomBBoxMargin: double, graphName: str, graphviz_size_scaling: int) -> None: ...
    def validate(self) -> None: ...
    def doGraphvizConvert(self) -> GraphLayoutIRResult: ...
    def doHolaConvert(self) -> GraphLayoutIRResult: ...
    def doColaConvert(self) -> GraphLayoutIRResult: ...
    def doColaSvgWrite(self, path: str) -> None: ...
    def doColaStrFormat(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> object: ...
    rectangles: List
    edges: List
    nodeConstraints: List
    subgraphs: List
    edgeLabels: Dict
    edgeConstraints: Dict
    width: double
    height: double
    leftBBoxMargin: double
    rightBBoxMargin: double
    topBBoxMargin: double
    bottomBBoxMargin: double
    graphName: str
    graphviz_size_scaling: int
