syntax = "proto3";

package hstd.ext.geometry.proto;

message Padding {
  double top = 1;
  double bottom = 2;
  double left = 3;
  double right = 4;
}

message Rect {
  double x = 1;
  double y = 2;
  double width = 3;
  double height = 4;
}

message Point {
  double x = 1;
  double y = 2;
}

message Path {
  enum CommandType {
    MOVE_TO = 0;
    LINE_TO = 1;
    QUAD_TO = 2;
    CUBIC_TO = 3;
    CLOSE_SUBPATH = 4;
  }

  message Command {
    CommandType type = 1;
    Point p1 = 2;
    Point p2 = 3;
    Point p3 = 4;
  }

  repeated Command commands = 1;
}

message Polygon {
  repeated Point points = 1;
}
