# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: reflection_defs.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AccessSpecifier",
    "Arg",
    "BaseSpec",
    "CvQual",
    "Enum",
    "EnumField",
    "Expr",
    "ExprKind",
    "Function",
    "Include",
    "IncludeVisit",
    "QualType",
    "Record",
    "RecordField",
    "RecordMethod",
    "RecordMethodKind",
    "ReferenceKind",
    "TemplateGroup",
    "TemplateParam",
    "TemplateParamKind",
    "TemplateParams",
    "Tu",
    "TypeKind",
    "TypeTag",
    "Typedef",
)

from dataclasses import dataclass

import betterproto2

from .message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class AccessSpecifier(betterproto2.Enum):
    AsPublic = 0

    AsProtected = 1

    AsPrivate = 2

    AsNone = 3


class ExprKind(betterproto2.Enum):
    Lit = 0


class RecordMethodKind(betterproto2.Enum):
    Base = 0

    CopyConstructor = 1

    MoveConstructor = 2

    CopyAssignmentOperator = 3

    MoveAssignmentOperator = 4

    Destructor = 5

    DefaultConstructor = 6

    ConvertingConstructor = 7

    Constructor = 8


class ReferenceKind(betterproto2.Enum):
    NotRef = 0

    LValue = 1

    RValue = 2


class TemplateParamKind(betterproto2.Enum):
    TYPE = 0

    NON_TYPE = 1

    TEMPLATE = 2

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "TEMPLATE_PARAM_KIND_TYPE",
            1: "TEMPLATE_PARAM_KIND_NON_TYPE",
            2: "TEMPLATE_PARAM_KIND_TEMPLATE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "TEMPLATE_PARAM_KIND_TYPE": 0,
            "TEMPLATE_PARAM_KIND_NON_TYPE": 1,
            "TEMPLATE_PARAM_KIND_TEMPLATE": 2,
        }


class TypeKind(betterproto2.Enum):
    RegularType = 0

    FunctionPtr = 1
    """
    Pointer to standalone function -- not pointer to member.
    Return type is stored as a first argument, parameter types
    are provided as trailing arguments
    """

    Array = 2
    """
    Pointer to class method. Return type is stored as a first
    parameter, class type is a second, argument are trailing.
    """

    TypeExpr = 3


class TypeTag(betterproto2.Enum):
    TypeTagNone = 0

    TypeTagStruct = 1

    TypeTagEnum = 2

    TypeTagUnion = 3


@dataclass(eq=False, repr=False)
class Arg(betterproto2.Message):
    type: "QualType | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    default: "Expr | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    doc: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)


default_message_pool.register_message("", "Arg", Arg)


@dataclass(eq=False, repr=False)
class BaseSpec(betterproto2.Message):
    name: "QualType | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_virtual: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    access: "AccessSpecifier" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: AccessSpecifier(0)
    )


default_message_pool.register_message("", "BaseSpec", BaseSpec)


@dataclass(eq=False, repr=False)
class CvQual(betterproto2.Message):
    is_pointer: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    is_const: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    is_volatile: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message("", "CVQual", CvQual)


@dataclass(eq=False, repr=False)
class Enum(betterproto2.Message):
    """
    Enumeration definition
    """

    fields: "list[EnumField]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    name: "QualType | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    base: "QualType | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    doc: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    enum_def_name: "QualType | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    / In case enumeration was defined in C context, under both typedef and own name
    / both are stored in the result. Generated data aims to have the most easily accessible
    / 'name' for the enumeration declaration in the `Name` field, but if there is more data
    / in the construction then it is pushed here.
    """

    is_forward_decl: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)

    reflection_params: "google_protobuf.Struct | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_described_enum: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)
    """
    / Class has boost description annotations
    """


default_message_pool.register_message("", "Enum", Enum)


@dataclass(eq=False, repr=False)
class EnumField(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    value: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)


default_message_pool.register_message("", "Enum.Field", EnumField)


@dataclass(eq=False, repr=False)
class Expr(betterproto2.Message):
    """
    Simplified representation of arbitrary expression
    """

    kind: "ExprKind" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ExprKind(0)
    )

    value: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    sub: "list[Expr]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, repeated=True)


default_message_pool.register_message("", "Expr", Expr)


@dataclass(eq=False, repr=False)
class Function(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    result_ty: "QualType | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    arguments: "list[Arg]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    templates: "list[TemplateParams]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    dbg_origin: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    spaces: "list[QualType]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )

    reflection_params: "google_protobuf.Struct | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "Function", Function)


@dataclass(eq=False, repr=False)
class Include(betterproto2.Message):
    relative_path: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    absolute_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("", "Include", Include)


@dataclass(eq=False, repr=False)
class IncludeVisit(betterproto2.Message):
    relative_path: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    absolute_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    / normalized absolute path to the included file.
    """

    file_line_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)

    used_line_count: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    """
    / Direct lines expanded from the included file,
    / excluding all nested files.
    """

    include_location_line: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    """
    / where in the file include happened
    """

    nested: "list[IncludeVisit]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "IncludeVisit", IncludeVisit)


@dataclass(eq=False, repr=False)
class QualType(betterproto2.Message):
    """
    Fully qualified C++ type that is designed to uniquely identify the target
    within a single translation unit. More complex cases are not considered
    (duplicate type names in different files, across different projects)
    """

    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    Unmangled type name
    """

    spaces: "list[QualType]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    List of wrapping spaces that would allow to uniquely jump to the
    type. If something was implicit in the code it will still be listed
    fully here.
    """

    parameters: "list[QualType]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    List of template type parameters for the type instance. Qualified types
    that are used as parent types can also have parameters.
    """

    qualifiers: "list[CvQual]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    ref_kind: "ReferenceKind" = betterproto2.field(
        5, betterproto2.TYPE_ENUM, default_factory=lambda: ReferenceKind(0)
    )
    """
    `T&` vs `T&` (TODO r-value ref)
    """

    kind: "TypeKind" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: TypeKind(0)
    )

    type_value: "Expr | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_namespace: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)
    """
    `std::vector` -- std will also be handled as qualified type to
    avoid making more complicated spaces structure. TODO revise if
    `repeated string Spaces` + `repated QualType Parents` will be
    a better alternative.
    """

    dbg_origin: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)

    tag: "TypeTag" = betterproto2.field(
        10, betterproto2.TYPE_ENUM, default_factory=lambda: TypeTag(0)
    )

    is_builtin: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)

    is_typedef: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)

    is_global_namespace: "bool" = betterproto2.field(13, betterproto2.TYPE_BOOL)

    is_template_type_param: "bool" = betterproto2.field(14, betterproto2.TYPE_BOOL)

    is_template_injected_type: "bool" = betterproto2.field(15, betterproto2.TYPE_BOOL)


default_message_pool.register_message("", "QualType", QualType)


@dataclass(eq=False, repr=False)
class Record(betterproto2.Message):
    name: "QualType | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    / Name can be truly absent here, in case of `union {int a; char b};` that is
    / used to splice inner members or for similar C-style approaches to the code
    / building.
    """

    bases: "list[BaseSpec]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    fields: "list[RecordField]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    methods: "list[RecordMethod]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    nested_rec: "list[Record]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )

    nested_enum: "list[Enum]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )

    nested_typedef: "list[Typedef]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, repeated=True
    )

    doc: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)

    templates: "list[TemplateParams]" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, repeated=True
    )

    record_def_name: "QualType | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    / See 'EnumDefName' description in the enumeration message.
    """

    is_forward_decl: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)

    is_union: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)
    """
    / Unions share most of the features with the regular records, so it is easier
    / to introduce a side channel here. List of bases would be unnecessary, but
    / everything else can still be used in enum.
    """

    has_name: "bool" = betterproto2.field(13, betterproto2.TYPE_BOOL)
    """
    / Python protobuf generator I had to use to get type annotations does not support
    / optional types (not important, I know), so I need to hack it around as a boolean
    / field here.
    """

    is_abstract: "bool" = betterproto2.field(14, betterproto2.TYPE_BOOL)

    reflection_params: "google_protobuf.Struct | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_explicit_instantiation: "bool" = betterproto2.field(16, betterproto2.TYPE_BOOL)

    is_template_record: "bool" = betterproto2.field(17, betterproto2.TYPE_BOOL)

    explicit_template_params: "list[QualType]" = betterproto2.field(
        18, betterproto2.TYPE_MESSAGE, repeated=True
    )

    is_described_record: "bool" = betterproto2.field(19, betterproto2.TYPE_BOOL)
    """
    / The type has boost descirbe annotations either in form of `BOOST_DESCRIBE_CLASS` or `BOOST_DESCRIBE_STRUCT`
    """


default_message_pool.register_message("", "Record", Record)


@dataclass(eq=False, repr=False)
class RecordField(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    doc: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    type: "QualType | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    type_decl: "Record | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    is_type_decl: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    reflection_params: "google_protobuf.Struct | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "Record.Field", RecordField)


@dataclass(eq=False, repr=False)
class RecordMethod(betterproto2.Message):
    return_ty: "QualType | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    args: "list[Arg]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True)

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    is_const: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    is_static: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    is_virtual: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)

    is_pure_virtual: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    is_implicit: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)

    is_operator: "bool" = betterproto2.field(9, betterproto2.TYPE_BOOL)

    kind: "RecordMethodKind" = betterproto2.field(
        10, betterproto2.TYPE_ENUM, default_factory=lambda: RecordMethodKind(0)
    )

    doc: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)

    operator_name: "str" = betterproto2.field(12, betterproto2.TYPE_STRING)

    reflection_params: "google_protobuf.Struct | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "Record.Method", RecordMethod)


@dataclass(eq=False, repr=False)
class TemplateGroup(betterproto2.Message):
    params: "list[TemplateParam]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "TemplateGroup", TemplateGroup)


@dataclass(eq=False, repr=False)
class TemplateParam(betterproto2.Message):
    kind: "TemplateParamKind" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: TemplateParamKind(0)
    )

    type_expr: "QualType | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    variadic: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    concept: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    default: "list[QualType]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )

    template_params: "list[TemplateParams]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )

    non_type_constraint: "list[QualType]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "TemplateParam", TemplateParam)


@dataclass(eq=False, repr=False)
class TemplateParams(betterproto2.Message):
    stacks: "list[TemplateGroup]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "TemplateParams", TemplateParams)


@dataclass(eq=False, repr=False)
class Tu(betterproto2.Message):
    records: "list[Record]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    enums: "list[Enum]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True)

    functions: "list[Function]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    typedefs: "list[Typedef]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    includes: "list[Include]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )

    absolute_path: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    doc: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)

    main_file_include_tree: "IncludeVisit | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "TU", Tu)


@dataclass(eq=False, repr=False)
class Typedef(betterproto2.Message):
    name: "QualType | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    / Fully qualified name of the type definition -- trailing name and all parent scopes
    """

    base_type: "QualType | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    / Base type used in declaration
    """

    templates: "list[TemplateParams]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    reflection_params: "google_protobuf.Struct | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "Typedef", Typedef)


from .google import protobuf as google_protobuf
