[project]
name = "hstd_py_codegen"
version = "0.1.0"
description = ""
authors = [{name = "haxscramper", email = "haxscramper@gmail.com"}]
readme = {file = "README.org", content-type = "text/plain"}
requires-python = ">=3.13,<3.14"
dependencies = [
  "hstd_py_lib",
  "hstd_py_text_layout",
  "graphviz",
  "igraph",
  "betterproto2",
]

[dependency-groups]
dev = [
  "pytest",
]

[build-system]
requires = [
  "hatchling",
  "hstd_py_lib",
  "conan>=2",
  "grpcio-tools",
  "betterproto2-compiler",
]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.conan]
reference = "haxdex_read_code_cpp/0.1.0"
editable-root = "src"

[[tool.hatch.build.hooks.conan.artifacts]]
artifact = "haxdex_read_code_cpp"
package_type = "application"

# exclude sources generated in the editable build
# otherwise the full package triggers a conflict
[tool.hatch.build.targets.wheel]
exclude = ["/src/hstd_py_codegen/proto"]

[tool.hatch.build.hooks.conan.protobuf]
sources = ["haxdex_read_code_cpp/reflection_defs.proto"]
destination = "hstd_py_codegen/proto"
well-known-sources = ["google/protobuf/struct.proto"]
