[build-system]
requires = [
  "hatchling>=1.27",
  "hstd_py_lib==0.1.0",
]
build-backend = "hatchling.build"

[project]
name = "hstd_py_text_layout"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "hstd_py_lib==0.1.0",
]

[dependency-groups]
dev = [
  "pytest",
]

[tool.uv.sources]
hstd_py_lib = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/hstd_py_text_layout"]

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/tests",
  "/pyproject.toml",
]

[tool.hatch.build.hooks.conan]
reference = "hstd_cpp_text_layout_py_wrap/0.1.0"
artifact = "hstd_cpp_text_layout_py_wrap*.so"
destination = ""
