syntax = "proto3";
import "google/protobuf/any.proto";
import "google/protobuf/struct.proto";
import "src/haxorg/serde/SemOrgProto.proto";
import "src/haxorg/serde/OrgApiProto.proto";
import "src/hstd/ext/error_write.proto";
import "src/hstd/ext/graph/base/graph_base.proto";

package org.graph.proto;

message MapNodePayload {
  orgproto.AnyNode node = 1;
}

message MapEdgePayload {
  enum EdgeKind {
    DIRECT_LINK = 0;
    NESTED_STATEMENT_ELEMENT = 1;
    NESTED_SUBTREE = 2;
    DESCRIPTION_LIST_HEAD = 3;
  }

  EdgeKind kind = 1;
}


message MapEdgeCollectionPayload {

};

message GraphResult {
  .hstd.ext.graph.proto.IGraph graph = 1;
  repeated .orgproto.ParseReport reports = 2;
  .orgproto.SourceManager sources = 3;
}
