[project]
name = "haxdex_read_code_cpp_pytest_package"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "pytest>=8.4.2",
  "hstd_py_lib",
  "beartype",
  "plumbum",
  "betterproto2",
]

[build-system]
requires = [
  "hatchling",
  "beartype",
  "plumbum",
  "grpcio-tools",
  "betterproto2-compiler",
]
build-backend = "hatchling.build"

[tool.uv]
package = true
cache-keys = [
  { file = "pyproject.toml" },
  { file = "hatch_build.py" },
  { file = "../proto/haxdex_read_code_cpp/reflection_defs.proto" },
]

[tool.hatch.build]
artifacts = ["proto/**"]

[tool.hatch.build.targets.wheel]
packages = ["proto/haxdex_read_code_cpp"]
dev-mode-dirs = ["proto"]

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"
output-dir = "proto"

[tool.pytest.ini_options]
testpaths = ["."]
addopts = "--color=yes"
markers = [
  "test_release: Reduced test suite done from the packaged release",
]
