from pathlib import Path

from beartype.typing import cast, List, Mapping, Tuple
from pydantic import BaseModel
from sphinx.builders import Builder
from sphinx.domains.python import ModuleEntry, PythonDomain
from sphinx.util import logging

logger = logging.getLogger(__name__)


class PyObject(BaseModel):
    "Single Python-domain object entry (function/class/method/etc.) exported by Sphinx."
    name: str
    "Fully-qualified object name (domain key, e.g. 'pkg.mod.Class.method')."
    display_name: str
    "Human-readable name as presented by Sphinx."
    type: str
    "Python domain object type (e.g. 'module', 'class', 'function', 'method')."
    docname: str
    "Source Sphinx document name where the object is declared."
    anchor: str
    "Anchor/id within the document for deep-linking to this object."
    priority: int
    "Sphinx domain priority used for resolving ambiguous names."


class PyModule(BaseModel):
    "Python module entry exported by the Sphinx Python domain."
    name: str
    "Fully-qualified module name (e.g. 'pkg.mod')."
    docname: str
    "Source Sphinx document name where the module is described."
    synopsis: str
    "Short module synopsis (if provided in documentation)."
    platform: str
    "Target platform string (if provided in documentation)."
    deprecated: bool
    "Whether the module is marked as deprecated."


class StructJSONPayload(BaseModel):
    "Top-level JSON document containing project metadata and extracted Python-domain inventory."
    project: str
    "Sphinx project name."
    version: str
    "Sphinx version string (typically major/minor)."
    release: str
    "Sphinx release string (typically full version)."
    modules: List[PyModule]
    "All discovered modules from the Python domain."
    objects: List[PyObject]
    "All discovered objects from the Python domain."


class StructJSONBuilder(Builder):
    """Structured JSON backend builder for Sphinx."""
    name = "structjson"  # nodoc
    format = "json"  # nodoc
    epilog = "Wrote api.json"  # nodoc

    def init(self) -> None:
        "Initialize builder state and resolve the output directory path."
        self._outdir = Path(self.outdir)

    def get_outdated_docs(self):
        "Force a full rebuild so the single JSON payload always reflects current state."
        return "all"

    def get_target_uri(self, docname: str, typ: str | None = None) -> str:
        "Return an empty URI since this builder does not emit per-document pages."
        return ""

    def prepare_writing(self, docnames) -> None:
        "No-op: this builder only emits a single JSON file in `finish()`."
        pass

    def write_doc(self, docname: str, doctree) -> None:
        "No-op: per-document output is not generated by this builder."
        pass

    def finish(self) -> None:
        "Collect Python domain inventory and write it as `api.json` to the output directory."
        py_domain = self.env.domains.get("py")
        if py_domain is None:
            raise RuntimeError("Python domain is not available")

        py = cast(PythonDomain, py_domain)

        objects: List[PyObject] = []
        py_objects: List[Tuple[str, str, str, str, str, int]] = list(py.get_objects())
        for name, dispname, objtype, docname, anchor, priority in py_objects:
            objects.append(
                PyObject(
                    name=name,
                    display_name=dispname,
                    type=objtype,
                    docname=docname,
                    anchor=anchor,
                    priority=priority,
                ))

        modules: List[PyModule] = []
        modules_data: Mapping[str, ModuleEntry] = cast(
            Mapping[str, ModuleEntry],
            py.data.get("modules", {}),
        )

        for modname, modinfo in modules_data.items():
            modules.append(
                PyModule(
                    name=modname,
                    docname=modinfo.docname,
                    synopsis=modinfo.synopsis,
                    platform=modinfo.platform,
                    deprecated=bool(modinfo.deprecated),
                ))

        payload = StructJSONPayload(
            project=self.config.project,
            version=self.config.version,
            release=self.config.release,
            modules=sorted(modules, key=lambda x: x.name),
            objects=sorted(objects, key=lambda x: (x.type, x.name)),
        )

        self._outdir.mkdir(parents=True, exist_ok=True)
        out = self._outdir / "api.json"
        out.write_text(payload.model_dump_json(indent=2) + "\n", encoding="utf-8")
        logger.info("wrote %s", out)


def setup(app):
    "entry point for the sphinx extension"
    app.add_builder(StructJSONBuilder)
    return {"version": "0.1", "parallel_read_safe": True, "parallel_write_safe": True}
