# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: google/protobuf/struct.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("ListValue", "NullValue", "Struct", "Value")

import typing
from dataclasses import dataclass

import betterproto2
from typing_extensions import Self

from ...message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class NullValue(betterproto2.Enum):
    """
    Represents a JSON `null`.

    `NullValue` is a sentinel, using an enum with only one value to represent
    the null value for the `Value` type union.

    A field of type `NullValue` with any value other than `0` is considered
    invalid. Most ProtoJSON serializers will emit a Value with a `null_value` set
    as a JSON `null` regardless of the integer value, and so will round trip to
    a `0` value.
    """

    NULL_VALUE = 0
    """
    Null value.
    """


@dataclass(eq=False, repr=False)
class ListValue(betterproto2.Message):
    """
    Represents a JSON array.
    """

    values: "list[Value]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    Repeated field of dynamically typed values.
    """

    @classmethod
    def from_dict(cls, value, *, ignore_unknown_fields: bool = False) -> Self:
        return cls(values=[Value.from_dict(v) for v in value])

    def to_dict(
        self,
        *,
        output_format: betterproto2.OutputFormat = betterproto2.OutputFormat.PROTO_JSON,
        casing: betterproto2.Casing = betterproto2.Casing.CAMEL,
        include_default_values: bool = False,
    ) -> dict[str, typing.Any] | typing.Any:
        # If the output format is PYTHON, we should have kept the wrapped type without building the real class
        assert output_format == betterproto2.OutputFormat.PROTO_JSON

        return [value.to_dict() for value in self.values]


default_message_pool.register_message("google.protobuf", "ListValue", ListValue)


@dataclass(eq=False, repr=False)
class Struct(betterproto2.Message):
    """
    Represents a JSON object.

    An unordered key-value map, intending to perfectly capture the semantics of a
    JSON object. This enables parsing any arbitrary JSON payload as a message
    field in ProtoJSON format.

    This follows RFC 8259 guidelines for interoperable JSON: notably this type
    cannot represent large Int64 values or `NaN`/`Infinity` numbers,
    since the JSON format generally does not support those values in its number
    type.

    If you do not intend to parse arbitrary JSON into your message, a custom
    typed message should be preferred instead of using this type.
    """

    fields: "dict[str, Value]" = betterproto2.field(
        1,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE
        ),
    )
    """
    Unordered map of dynamically typed values.
    """

    @classmethod
    def from_dict(cls, value, *, ignore_unknown_fields: bool = False) -> Self:
        assert isinstance(value, dict)

        fields: dict[str, Value] = {}

        for key, val in value.items():
            fields[key] = Value.from_dict(val)

        return cls(fields=fields)  # type: ignore[reportArgumentType]

    def to_dict(
        self,
        *,
        output_format: betterproto2.OutputFormat = betterproto2.OutputFormat.PROTO_JSON,
        casing: betterproto2.Casing = betterproto2.Casing.CAMEL,
        include_default_values: bool = False,
    ) -> dict[str, typing.Any] | typing.Any:
        # If the output format is PYTHON, we should have kept the wrapped type without building the real class
        assert output_format == betterproto2.OutputFormat.PROTO_JSON

        return {
            key: value.to_dict(
                output_format=output_format,
                casing=casing,
                include_default_values=include_default_values,
            )
            for key, value in self.fields.items()
        }


default_message_pool.register_message("google.protobuf", "Struct", Struct)


@dataclass(eq=False, repr=False)
class Value(betterproto2.Message):
    """
    Represents a JSON value.

    `Value` represents a dynamically typed value which can be either
    null, a number, a string, a boolean, a recursive struct value, or a
    list of values. A producer of value is expected to set one of these
    variants. Absence of any variant is an invalid state.

    Oneofs:
        - kind: The kind of value.
    """

    null_value: "NullValue | None" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, optional=True, group="kind"
    )
    """
    Represents a JSON `null`.
    """

    number_value: "float | None" = betterproto2.field(
        2, betterproto2.TYPE_DOUBLE, optional=True, group="kind"
    )
    """
    Represents a JSON number. Must not be `NaN`, `Infinity` or
    `-Infinity`, since those are not supported in JSON. This also cannot
    represent large Int64 values, since JSON format generally does not
    support them in its number type.
    """

    string_value: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True, group="kind"
    )
    """
    Represents a JSON string.
    """

    bool_value: "bool | None" = betterproto2.field(
        4, betterproto2.TYPE_BOOL, optional=True, group="kind"
    )
    """
    Represents a JSON boolean (`true` or `false` literal in JSON).
    """

    struct_value: "Struct | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
    )
    """
    Represents a JSON object.
    """

    list_value: "ListValue | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
    )
    """
    Represents a JSON array.
    """

    @classmethod
    def from_dict(cls, value, *, ignore_unknown_fields: bool = False) -> Self:
        match value:
            case bool() as b:
                return cls(bool_value=b)
            case int() | float() as num:
                return cls(number_value=num)
            case str() as s:
                return cls(string_value=s)
            case list() as l:
                return cls(list_value=ListValue.from_dict(l))
            case dict() as d:
                return cls(struct_value=Struct.from_dict(d))
            case None:
                return cls(null_value=NullValue.NULL_VALUE)
        raise ValueError(f"Unknown value type: {type(value)}")

    def to_dict(
        self,
        *,
        output_format: betterproto2.OutputFormat = betterproto2.OutputFormat.PROTO_JSON,
        casing: betterproto2.Casing = betterproto2.Casing.CAMEL,
        include_default_values: bool = False,
    ) -> dict[str, typing.Any] | typing.Any:
        # If the output format is PYTHON, we should have kept the wrapped type without building the real class
        assert output_format == betterproto2.OutputFormat.PROTO_JSON

        match self:
            case Value(null_value=NullValue.NULL_VALUE):
                return None
            case Value(bool_value=bool(b)):
                return b
            case Value(number_value=int(num)) | Value(number_value=float(num)):
                return num
            case Value(string_value=str(s)):
                return s
            case Value(list_value=ListValue(values=l)):
                return [v.to_dict() for v in l]
            case Value(struct_value=Struct(fields=f)):
                return {k: v.to_dict() for k, v in f.items()}

        raise ValueError("Invalid value")


default_message_pool.register_message("google.protobuf", "Value", Value)
