[build-system]
requires = [
  "hatchling>=1.27",
  "hstd_py_lib==0.1.0",
]
build-backend = "hatchling.build"

[project]
name = "haxorg_py_lib"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "hstd_py_lib==0.1.0",
  "dominate", # HTML exporter,
  "toml",
  "hstd_py_text_layout", # TODO: Auto-bump minimum version
]

[dependency-groups]
dev = [
  "pytest",
  "pytest-cov",
  "coverage",
  "ansi2html",
]

[tool.hatch.build.targets.wheel]
packages = ["src/haxorg_py_lib"]

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/tests",
  "/pyproject.toml",
]

[tool.hatch.build.hooks.conan]
reference = "haxorg_cpp_py_wrap/0.1.0"

[[tool.hatch.build.hooks.conan.artifacts]]
artifact = "python/haxorg_cpp_py_wrap*.so"
destination = ""
