
set(PROJ_ROOT "${CMAKE_SOURCE_DIR}")
set(REPO_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../../..")
set(DEPS_INSTALL "${REPO_ROOT}/build/deps_bin/install")
message(STATUS "${DEPS_INSTALL}")

include("${DEPS_INSTALL}/paths.cmake")
list(INSERT CMAKE_PREFIX_PATH 0 "${REPO_ROOT}/build/install")

find_package(Immer CONFIG REQUIRED)
find_package(Lager CONFIG REQUIRED)
find_package(absl CONFIG REQUIRED)
find_package(protobuf CONFIG REQUIRED)
find_package(boost_mp11 CONFIG REQUIRED)
find_package(BoostDescribe CONFIG REQUIRED)
find_package(range-v3 CONFIG REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
find_package(OpenGL REQUIRED)
find_package(Perfetto CONFIG REQUIRED)
find_package(lexy CONFIG REQUIRED)
find_package(yaml-cpp CONFIG REQUIRED)
find_package(Adaptagrams CONFIG REQUIRED)
find_package(cctz REQUIRED)
find_package(msgpack-cxx CONFIG REQUIRED)
find_package(Boost REQUIRED COMPONENTS ALL)
find_package(cpptrace CONFIG REQUIRED)
find_package(BoostDescribe CONFIG REQUIRED)
find_package(BoostPreprocessor CONFIG REQUIRED)
find_package(Haxorg CONFIG REQUIRED)
