syntax = "proto3";

import "google/protobuf/any.proto";
import "google/protobuf/struct.proto";
import "hstd/ext/geometry/hstd_geometry.proto";
import "hstd/ext/geometry/hstd_visual.proto";
import "hstd/ext/graph/base/graph_base.proto";
import "hstd/ext/graph/visual/graph_visual.proto";
import "hstd/ext/geometry/kiwi_ir.proto";

package hstd.ext.graph.kw.proto;

message KiwiPortVisualAttributePayload {
  hstd.ext.graph.layout.proto.IPortVisualAttributePayload base = 1;
}

message KiwiPortLayoutAttributePayload {
  hstd.ext.graph.layout.proto.IPortLayoutAttributePayload base = 1;
}

message KiwiEdgeVisualAttributePayload {
  hstd.ext.graph.layout.proto.IEdgeVisualAttributePayload base = 1;
}

message KiwiEdgeLayoutAttributePayload {
  hstd.ext.graph.layout.proto.IEdgeLayoutAttributePayload base = 1;
}

message KiwiVertexVisualAttributePayload {
  hstd.ext.graph.layout.proto.IVertexVisualAttributePayload base             = 1;
  hstd.ext.kiwi_ir.proto.Rect                               rect             = 2;
  string                                                    parent_stable_id = 3;
}

message KiwiGroupVisualAttributePayload {
  hstd.ext.graph.layout.proto.IGroupVisualAttributePayload base             = 1;
  optional string                                          parent_stable_id = 3;
}

message KiwiVertexLayoutAttributePayload {
  hstd.ext.graph.layout.proto.IVertexLayoutAttributePayload base = 1;
}

message KiwiGroupLayoutAttributePayload {
  hstd.ext.graph.layout.proto.IGroupLayoutAttributePayload base = 1;
}

message KiwiConstraintPayloadBase {
  hstd.ext.kiwi_ir.proto.Strength strength = 1;
}

message KiwiAlignConstraintPayload {
  message Spec {
    string                           stable_vertex_id = 1;
    hstd.ext.kiwi_ir.proto.AlignSpec spec             = 2;
  }

  KiwiConstraintPayloadBase   base      = 1;
  repeated Spec               vertices  = 2;
  hstd.ext.kiwi_ir.proto.Axis dimension = 3;
}

message KiwiSeparateConstraintPayload {
  KiwiConstraintPayloadBase   base               = 1;
  KiwiAlignConstraintPayload  left               = 2;
  KiwiAlignConstraintPayload  right              = 3;
  double                      separationDistance = 4;
  hstd.ext.kiwi_ir.proto.Axis dimension          = 5;
}

message KiwiMultiSeparateConstraintPayload {
  KiwiConstraintPayloadBase           base               = 1;
  repeated KiwiAlignConstraintPayload lines              = 2;
  double                              separationDistance = 3;
  hstd.ext.kiwi_ir.proto.Axis         dimension          = 4;
}

message KiwiLinearConstraintPayload {
  KiwiConstraintPayloadBase       base = 1;
  hstd.ext.kiwi_ir.proto.Expr     lhs  = 2;
  hstd.ext.kiwi_ir.proto.Expr     rhs  = 3;
  hstd.ext.kiwi_ir.proto.Relation op   = 4;
}

message KiwiRelativeConstraintPayload {
  message VertexRef {
    string                            stable_vertex_id = 1;
    hstd.ext.kiwi_ir.proto.AnchorSpec anchor           = 2;
  }

  VertexRef                               fixed    = 1;
  VertexRef                               relative = 2;
  hstd.ext.kiwi_ir.proto.RelDimensionSpec x_dim    = 3;
  hstd.ext.kiwi_ir.proto.RelDimensionSpec y_dim    = 4;
}
