syntax = "proto3";

package hstd.ext.graph.diagram.proto;

import "buf/validate/validate.proto";
import "google/protobuf/struct.proto";
import "src/hstd/ext/geometry/hstd_geometry.proto";
import "src/hstd/ext/graph/base/graph_base.proto";
import "src/hstd/ext/graph/visual/graph_elk.proto";
import "src/hstd/ext/graph/visual/graph_graphviz.proto";
import "src/hstd/ext/graph/visual/graph_kiwi.proto";

/*

   Simplified representation of the graph structure, for describing
   the diagram elements using nested elements.

   All coordinates are relative to the parent element.

*/

message DiaNode {
  string id = 1 [(buf.validate.field).string.min_len = 1];

  option (buf.validate.message).cel = {
    id: "dia_node.graphviz_dimensions_required"
    message: "graphviz width and height are required in the diagram context"
    expression: "!has(this.graphviz) || (has(this.graphviz.width) && has(this.graphviz.height))"
  };

  oneof kind {
    hstd.ext.graph.gv.proto.NodeAttributePayload graphviz = 2;
    hstd.ext.graph.kw.proto.KiwiVertexVisualAttributePayload kiwi = 3;
    hstd.ext.graph.elk.proto.ElkNodeVisualAttributePayload elk = 4;
  }

  optional hstd.ext.geometry.proto.Rect bbox = 5;
}

message DiaEdge {
  string source = 1 [(buf.validate.field).string.min_len = 1];
  string target = 2 [(buf.validate.field).string.min_len = 1];
  string id = 3 [(buf.validate.field).string.min_len = 1];

  oneof kind {
    hstd.ext.graph.gv.proto.EdgeAttributePayload graphviz = 4;
    hstd.ext.graph.kw.proto.KiwiEdgeVisualAttributePayload kiwi = 5;
    hstd.ext.graph.elk.proto.ElkEdgeVisualAttributePayload elk = 6;
  }

  optional hstd.ext.geometry.proto.Path path = 7;
}

message DiaConstraint {
  oneof kind {
    hstd.ext.graph.kw.proto.KiwiAlignConstraintPayload kw_align = 1;
    hstd.ext.graph.kw.proto.KiwiSeparateConstraintPayload kw_separate = 2;
    hstd.ext.graph.kw.proto.KiwiMultiSeparateConstraintPayload kw_multi_separate = 3;
    hstd.ext.graph.kw.proto.KiwiRelativeConstraintPayload kw_relative = 4;
    hstd.ext.graph.kw.proto.KiwiLinearConstraintPayload kw_linear = 5;
  }
}

message DiaCluster {
  option (buf.validate.message).cel = {
    id: "graphviz_no_kiwi_constraints"
    message: "a Graphviz cluster cannot contain Kiwi constraints"
    expression: "!has(this.graphviz) || this.constraints.size() == 0"
  };
  option (buf.validate.message).cel = {
    id: "element kind matches the payload kind"
    message: "edges must have a payload matching the cluster layout kind"
    expression:
      // Nodes and edges must match the graph algorithm if it is provided,
      // otherwise they must match the parent algorithm. Some additional
      // validation is performed at the C++ level, as CEL does not support
      // arbitrary recursion into the structure.
      "("
      "has(this.kiwi) && "
      "this.edges.all(e, has(e.kiwi)) && "
      "this.nodes.all(e, has(e.kiwi))"
      ")"
      "||"
      "("
      "has(this.graphviz) && "
      "this.edges.all(e, has(e.graphviz)) && "
      "this.nodes.all(e, has(e.graphviz))"
      ")"
      "||"
      "("
      "has(this.elk) && "
      "this.edges.all(e, has(e.elk)) && "
      "this.nodes.all(e, has(e.elk))"
      ")"
      "||"
      // If the layout on this specific graph is not provided, the elements must
      // still be internally consistent -- nested clusters can change the layout
      // algorithms at any moment, and they will be handled separately.
      "("
      "has(this.no_layout) && ("
      "("
      "this.edges.all(e, has(e.kiwi)) && "
      "this.nodes.all(n, has(n.kiwi))"
      ") || ("
      "this.edges.all(e, has(e.graphviz)) && "
      "this.nodes.all(n, has(n.graphviz))"
      ") || ("
      "this.edges.all(e, has(e.elk)) && "
      "this.nodes.all(n, has(n.elk))"
      ")"
      ")"
      ")"
  };

  string id = 1 [(buf.validate.field).string.min_len = 1];
  repeated DiaNode nodes = 2;
  repeated DiaEdge edges = 3;
  repeated DiaCluster nested = 4;
  repeated DiaConstraint constraints = 5;

  oneof kind {
    google.protobuf.NullValue no_algorithm = 6;
    hstd.ext.graph.gv.proto.GroupAttributePayload graphviz = 7;
    hstd.ext.graph.kw.proto.KiwiGroupVisualAttributePayload kiwi = 8;
    hstd.ext.graph.elk.proto.ElkGroupVisualAttributePayload elk = 9;
  }

  optional hstd.ext.geometry.proto.Rect bbox = 10;
}

message DiaGraphMetadata {
  map<string, bool> no_algorithm_cluster_ids = 1;
  map<string, string> edge_parent_cluster_ids = 2;
}
